import { ExplorerPlace } from "./canonical-places";

export const CHENNAI_EXPANDED_PLACES: Record<string, ExplorerPlace> = {
  // --- CHENNAI BEACHES & COASTAL PLACES ---
  "marina-beach": {
    id: "p-marina-beach",
    canonicalName: "Marina Beach",
    name: "Marina Beach",
    slug: "marina-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0499,
    longitude: 80.2824,
    categories: ["beaches", "coastal", "tourist-places"],
    primaryCategory: "beaches",
    tagline: "Second longest natural urban beach in the world stretching 13 km along Coromandel Coast",
    description: "Stretching from Fort St. George to Besant Nagar, Marina Beach is Chennai's iconic urban promenade featuring historic memorials, the Chennai Lighthouse, vibrant evening food stalls, and vast golden sands.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "marina", "chennai", "lighthouse", "promenade", "statues", "sunset", "family-friendly"],
    highlights: [
      "Chennai Lighthouse Viewpoint",
      "Iconic Memorial Statues (Triumph of Labour, Gandhi)",
      "Evening Street Food & Sundal Stalls",
      "Golden Sand Horizon"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:00 AM - 8:00 AM & 4:30 PM - 8:00 PM",
      duration: "2-3 hours",
      accessPermissions: "Open public beach. Swimming prohibited due to strong undercurrents."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Mylapore",
    nearbyTown: "Triplicane / Santhome",
    distanceFromChennaiKm: 2,
    durationFromChennaiHours: 0.1
  },
  "besant-nagar-beach": {
    id: "p-besant-nagar-beach",
    canonicalName: "Besant Nagar Beach (Elliot's Beach)",
    name: "Besant Nagar Beach (Elliot's Beach)",
    slug: "besant-nagar-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0002,
    longitude: 80.2668,
    categories: ["beaches", "coastal", "tourist-places"],
    primaryCategory: "beaches",
    tagline: "Cleaner, tranquil coastal promenade home to Karl Schmidt Memorial & vibrant beach cafes",
    description: "Locally known as 'Bessie', Elliot's Beach in Besant Nagar forms the southern endpoint of the Marina shore. Characterized by a relaxed atmosphere, the historical Dutch sailor Karl Schmidt Memorial, and trendy beachside cafes.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "besant_nagar", "elliots_beach", "bessie", "schmidt_memorial", "sunset", "photography"],
    highlights: [
      "Karl Schmidt Memorial Monument",
      "Spacious Quiet Beach Promenade",
      "Bessie Beach Food & Cafe Street",
      "Ashtalakshmi Temple at Shore North"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:30 AM & 4:00 PM - 9:00 PM",
      duration: "2 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Coastal",
    taluk: "Velachery",
    nearbyTown: "Besant Nagar",
    distanceFromChennaiKm: 11,
    durationFromChennaiHours: 0.3
  },
  "ecr-beach": {
    id: "p-ecr-beach",
    canonicalName: "ECR Coastal Beaches (Neelankarai & Palavakkam)",
    name: "ECR Beach",
    slug: "ecr-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9554,
    longitude: 80.2592,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Pristine, peaceful sandy shorelines along Palavakkam & Neelankarai",
    description: "Stretching along the residential coastal hamlets of Palavakkam, Neelankarai, and Akkarai, ECR Beach offers quiet, uncrowded stretches of golden sand away from central city crowds.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "ecr_beach", "neelankarai", "palavakkam", "quiet_beach", "sunset", "nature"],
    highlights: [
      "Uncrowded Clean Sand Shoreline",
      "Olive Ridley Sea Turtle Nesting Sites (Seasonal)",
      "Sunrise & Sunset Beach Walks",
      "Calm Residential Beach Vibe"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 7:30 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Neelankarai",
    distanceFromChennaiKm: 15,
    durationFromChennaiHours: 0.4
  },
  "n8-beach": {
    id: "p-n8-beach-kasimedu",
    canonicalName: "N8 Beach (Kasimedu Coastal Pier)",
    name: "N8 Beach",
    slug: "n8-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.1180,
    longitude: 80.2980,
    categories: ["beaches", "coastal"],
    primaryCategory: "beaches",
    tagline: "Offbeat North Chennai coastal stretch famed for sunrise views & fishing harbor pier",
    description: "N8 Beach is an offbeat coastal stretch in North Chennai near the Kasimedu Ennore Express Highway pier. Popular among local youth and morning walkers for dramatic sunrise panoramas over the Bay of Bengal and sea wall breakwaters.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation & Local Harbor Patrol",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 96,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "n8_beach", "kasimedu", "north_chennai", "sunrise", "photography", "rocky-shore"],
    highlights: [
      "Dramatic Bay of Bengal Sunrise",
      "Granite Breakwater Sea Wall Walk",
      "Local Fishing Catamaran Activity",
      "Uncrowded Coastal Photography Spot"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM",
      duration: "1 hour",
      accessPermissions: "Open public coast. Slippery rocks during high tide."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Royapuram",
    nearbyTown: "Kasimedu",
    distanceFromChennaiKm: 8,
    durationFromChennaiHours: 0.25
  },
  "kasimedu-beach": {
    id: "p-kasimedu-beach",
    canonicalName: "Kasimedu Beach & Fishing Harbour",
    name: "Kasimedu Beach",
    slug: "kasimedu-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.1245,
    longitude: 80.2995,
    categories: ["beaches", "coastal", "heritage"],
    primaryCategory: "beaches",
    tagline: "Vibrant fishing harbour beach famous for early morning fish auctions & granite pier walk",
    description: "Located in Royapuram, Kasimedu Fishing Harbour Beach is the pulsing heart of Chennai's marine fishing community. Visitors flock here at dawn for live catamaran boat arrivals, fresh seafood auctions, and walks along the extended harbor breakwater pier.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Fisheries Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "kasimedu", "fishing_harbour", "pier", "sunrise", "seafood", "north_chennai"],
    highlights: [
      "Live Dawn Catamaran Boat Arrivals",
      "Historic Kasimedu Seafood Auctions",
      "1 km Granite Pier Walk",
      "Authentic Marine Heritage Culture"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:00 AM - 9:00 AM",
      duration: "1.5 hours",
      accessPermissions: "Active industrial fishing harbor. Stay clear of boat launch paths."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Royapuram",
    nearbyTown: "Kasimedu",
    distanceFromChennaiKm: 9,
    durationFromChennaiHours: 0.25
  },
  "nettukuppam-beach": {
    id: "p-nettukuppam-beach",
    canonicalName: "Nettukuppam Beach & Broken Pier",
    name: "Nettukuppam Beach",
    slug: "nettukuppam-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.2268,
    longitude: 80.3340,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Northernmost tip of Chennai where Ennore Creek meets Bay of Bengal, famed for its broken pier",
    description: "Situated at the northern apex of Chennai in Ennore, Nettukuppam Beach is famous for its historic broken concrete pier extending into crashing sea waves. It offers breathtaking sea views where Ennore Creek meets the ocean, attracting photographers and solitude seekers.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation & Ennore Local Administration",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "nettukuppam", "broken_pier", "ennore", "north_chennai", "sunset", "photography"],
    highlights: [
      "Iconic Broken Pier Structure",
      "Ennore Creek & Ocean Estuary Confluence",
      "Secluded Peaceful Sea Horizon",
      "Coastal Solitude & Photography Spot"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "4:00 PM - 6:30 PM",
      duration: "2 hours",
      accessPermissions: "Open public beach. Broken pier has open edges; exercise caution."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Tiruvottiyur",
    nearbyTown: "Ennore (5 km)",
    distanceFromChennaiKm: 22,
    durationFromChennaiHours: 0.6
  },
  "pebble-beach": {
    id: "p-pebble-beach-ecr",
    canonicalName: "Pebble Beach (Injambakkam Coastal Shore)",
    name: "Pebble Beach",
    slug: "pebble-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9100,
    longitude: 80.2550,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Secluded rocky shoreline along ECR known for sea pebbles, granite boulders & wave foam",
    description: "Pebble Beach is a secluded natural beach strip located off ECR near Injambakkam. Featuring smooth sea stones, granite tide rocks, and crashing foam spray, it is a favorite quiet retreat away from commercial beach crowds.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Local Coastal Survey",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 95,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "pebble_beach", "injambakkam", "ecr", "rocky-shore", "nature", "photography"],
    highlights: [
      "Natural Granite Tide Boulders",
      "Smooth Sea Stone Shoreline",
      "Quiet Coastal Retreat",
      "Crashing Wave Photography"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "6:00 AM - 8:00 AM & 4:30 PM - 6:30 PM",
      duration: "1 hour",
      accessPermissions: "Open public coast access."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam",
    distanceFromChennaiKm: 18,
    durationFromChennaiHours: 0.5
  },
  "sadras-beach": {
    id: "p-sadras-beach",
    canonicalName: "Sadras Beach & 17th-Century Dutch Fort",
    name: "Sadras Beach",
    slug: "sadras-beach",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.5186,
    longitude: 80.1605,
    categories: ["beaches", "coastal", "heritage"],
    primaryCategory: "beaches",
    tagline: "Historic coastal beach adjacent to 17th-century Dutch brick fort ruins near Kalpakkam",
    description: "Located in Sadurangapattinam (Sadras) 70 km south of Chennai near Kalpakkam, Sadras Beach is a quiet coastal shore backed by a preserved 17th-century Dutch fortress, granaries, and colonial tombs.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Archaeological Survey of India (ASI) & Chengalpattu District Admin",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "sadras", "dutch_fort", "kalpakkam", "chengalpattu", "heritage", "sunset"],
    highlights: [
      "17th-Century Dutch Fort Ruins & Granary",
      "Colonial Dutch Cemetery & Inscriptions",
      "Serene Uncrowded Beach Shoreline",
      "Pristine Coastal Heritage Sunset"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "8:00 AM - 5:30 PM",
      duration: "2-3 hours",
      accessPermissions: "ASI protected monument. Open access."
    },
    travelOrigins: ["chennai"],
    nearbyTown: "Kalpakkam (5 km) / Chengalpattu (35 km)",
    distanceFromChennaiKm: 70,
    durationFromChennaiHours: 1.8
  },
  "alamparai-fort": {
    id: "p-alamparai-fort",
    canonicalName: "Alamparai Fort & Backwaters",
    name: "Alamparai Fort",
    slug: "alamparai-fort",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.2625,
    longitude: 79.9922,
    categories: ["heritage", "coastal", "tourist-places"],
    primaryCategory: "heritage",
    tagline: "Dramatic 18th-century Mughal-French ruin fortress overlooking pristine coastal backwaters",
    description: "Built in the 18th century by the Nawab of Arcot and later gifted to the French, Alamparai Fort in Kadapakkam stands as an evocative brick ruin surrounded by tranquil backwater lagoons, sea palm groves, and local catamaran boat trips.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Department of Archaeology & Chengalpattu District Admin",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:50:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["alamparai", "allambari", "fort", "backwaters", "kadapakkam", "chengalpattu", "ecr", "heritage"],
    highlights: [
      "Overgrown 18th-Century Brick Fort Ruins & Sea Watchtowers",
      "Backwater Boat Rides with Local Fishermen",
      "Estuary Confluence of Backwaters & Sea",
      "Scenic Coastal Heritage Photography Landscape"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "8:00 AM - 6:00 PM",
      duration: "2 hours",
      accessPermissions: "Protected state heritage site. Open public daytime access."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Cheyyur",
    nearbyTown: "Kadapakkam / Marakkanam (15 km)",
    distanceFromChennaiKm: 100,
    durationFromChennaiHours: 2.2
  },
  "karikattukuppam-beach": {
    id: "p-karikattukuppam-beach",
    canonicalName: "Karikattukuppam Coastal Beach",
    name: "Karikattukuppam Beach",
    slug: "karikattukuppam-beach",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8050,
    longitude: 80.2430,
    categories: ["beaches", "coastal"],
    primaryCategory: "beaches",
    tagline: "Tranquil eco-coastal fishing beach stretch near Muttukadu backwater mouth",
    description: "Nestled between Muttukadu backwaters and Kovalam along ECR, Karikattukuppam Beach is a serene, uncrowded fishing village shoreline with soft golden sand, catamarans, and gentle surf.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Chengalpattu District Admin",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 96,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "karikattukuppam", "muttukadu", "ecr", "quiet_beach", "family-friendly"],
    highlights: [
      "Muttukadu Backwater Estuary View",
      "Peaceful Golden Sand Shoreline",
      "Traditional Catamaran Fishing Village",
      "Quiet Evening Breeze Walk"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "4:30 PM - 7:00 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Thiruporur",
    nearbyTown: "Kovalam / Muttukadu (3 km)",
    distanceFromChennaiKm: 32,
    durationFromChennaiHours: 0.8
  },
  "covelong-beach": {
    id: "p-covelong-beach",
    canonicalName: "Covelong Beach (Kovalam Surfing Hub)",
    name: "Covelong Beach",
    slug: "covelong-beach",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.7915,
    longitude: 80.2505,
    categories: ["beaches", "coastal", "adventure"],
    primaryCategory: "beaches",
    tagline: "Premier surfing paradise, windsurfing school & historic Dutch fort resort on ECR",
    description: "Located 35 km south of Chennai in Kovalam village, Covelong Beach is South India's premier surfing destination. Famed for Covelong Point Surfing School, annual surf music festivals, catamarans, and Taj Fisherman's Cove heritage fort.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Tamil Nadu Tourism & Covelong Point Surf School",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "covelong", "kovalam", "surfing", "water-sports", "ecr", "chengalpattu", "adventure"],
    highlights: [
      "Covelong Point Surfing Academy",
      "Windsurfing & Stand-Up Paddleboarding",
      "Historic Dutch Fort Walls (Fisherman's Cove)",
      "Catamaran Sea Rides with Local Fishermen"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "6:00 AM - 9:00 AM (Surfing) & 4:00 PM - 7:00 PM",
      duration: "Half day",
      accessPermissions: "Open beach. Surfing lessons require advance booking."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Thiruporur",
    nearbyTown: "Kovalam / Mahabalipuram",
    distanceFromChennaiKm: 35,
    durationFromChennaiHours: 0.9
  },
  "santhome-beach": {
    id: "p-santhome-beach",
    canonicalName: "Santhome Beach",
    name: "Santhome Beach",
    slug: "santhome-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0330,
    longitude: 80.2780,
    categories: ["beaches", "coastal"],
    primaryCategory: "beaches",
    tagline: "Quieter, reflective coastal extension of Marina located directly behind historic Santhome Cathedral",
    description: "Santhome Beach is a peaceful, uncrowded sandy stretch tucked directly behind the historic neo-Gothic Santhome Cathedral Basilica. Offers serene ocean views and a calm atmosphere away from central Marina crowds.",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "santhome", "santhome_cathedral", "mylapore", "quiet_beach", "sunset", "chennai"],
    highlights: [
      "Behind Historic Santhome Cathedral Basilica",
      "Tranquil Sandy Shoreline",
      "Quiet Evening Promenade",
      "Pristine Sea Horizon Views"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 7:30 PM",
      duration: "1 hour",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Mylapore",
    nearbyTown: "Santhome / Mylapore",
    distanceFromChennaiKm: 4,
    durationFromChennaiHours: 0.15
  },
  "n4-beach": {
    id: "p-n4-beach",
    canonicalName: "N4 Beach (Tondiarpet Pier)",
    name: "N4 Beach",
    slug: "n4-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.1210,
    longitude: 80.2985,
    categories: ["beaches", "coastal"],
    primaryCategory: "beaches",
    tagline: "Scenic concrete breakwater pier next to Kasimedu fishing harbour lined with colorful catamarans",
    description: "Located in Tondiarpet right next to Kasimedu harbour, N4 Beach features long concrete groynes stretching into the ocean, colorful fishing boats, crashing waves, and coastal breeze.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "n4_beach", "tondiarpet", "kasimedu", "north_chennai", "pier", "groynes"],
    highlights: [
      "Long Concrete Groyne Breakwaters",
      "Colorfully Painted Fishing Catamarans",
      "Crashing Wave Foam Views",
      "North Chennai Coastal Sunrise"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 6:30 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public coast."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Tondiarpet",
    nearbyTown: "Kasimedu",
    distanceFromChennaiKm: 8,
    durationFromChennaiHours: 0.2
  },
  "thiruvanmiyur-beach": {
    id: "p-thiruvanmiyur-beach",
    canonicalName: "Thiruvanmiyur Beach",
    name: "Thiruvanmiyur Beach",
    slug: "thiruvanmiyur-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9845,
    longitude: 80.2640,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Tranquil, wide golden sand shore favored by morning walkers, fitness enthusiasts & yoga practitioners",
    description: "Thiruvanmiyur Beach is a spacious, uncrowded residential shoreline south of Besant Nagar. Known for its pristine morning air, gentle tide, and calm atmosphere favored for jogging and sunrise meditation.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "thiruvanmiyur", "thiruvanmiyur_beach", "yoga", "jogging", "sunrise", "chennai"],
    highlights: [
      "Spacious Golden Sand Shore",
      "Morning Jogging & Yoga Haven",
      "Calm Residential Atmosphere",
      "Clean Sea Breeze"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:00 AM - 8:30 AM & 4:30 PM - 8:00 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Coastal",
    taluk: "Velachery",
    nearbyTown: "Thiruvanmiyur",
    distanceFromChennaiKm: 12,
    durationFromChennaiHours: 0.35
  },
  "breezy-beach": {
    id: "p-breezy-beach",
    canonicalName: "Breezy Beach (Valmiki Nagar)",
    name: "Breezy Beach",
    slug: "breezy-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9810,
    longitude: 80.2635,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Small, hidden, uncrowded coastal pocket in Valmiki Nagar known for serene & peaceful environment",
    description: "Tucked quietly in Valmiki Nagar, Thiruvanmiyur, Breezy Beach is a clean, tranquil hideaway. Away from commercial street vendors, it offers a peaceful haven for reading, quiet walks, and ocean breezes.",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "breezy_beach", "valmiki_nagar", "thiruvanmiyur", "quiet_beach", "hidden_gem"],
    highlights: [
      "Hidden Residential Beach Pocket",
      "Quiet Ocean Solitude",
      "Pristine Uncluttered Sand",
      "Serene Sunrise Walk"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 7:30 PM",
      duration: "1 hour",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Coastal",
    taluk: "Velachery",
    nearbyTown: "Valmiki Nagar",
    distanceFromChennaiKm: 13,
    durationFromChennaiHours: 0.35
  },
  "kottivakkam-beach": {
    id: "p-kottivakkam-beach",
    canonicalName: "Kottivakkam Beach",
    name: "Kottivakkam Beach",
    slug: "kottivakkam-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9680,
    longitude: 80.2615,
    categories: ["beaches", "coastal"],
    primaryCategory: "beaches",
    tagline: "Wide, open expanse of clean sand serving as a calm, relaxed alternative for families along ECR",
    description: "Kottivakkam Beach features a broad shoreline with soft sand and open ocean vistas. Situated right off the East Coast Road, it provides a quiet setting for family weekend evening walks.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "kottivakkam", "kottivakkam_beach", "ecr", "family_friendly"],
    highlights: [
      "Wide Open Sand Expanse",
      "Calm Family Gathering Spot",
      "Clean Sea Breeze Promenade",
      "Uncrowded ECR Shore"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "4:30 PM - 7:30 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Kottivakkam",
    distanceFromChennaiKm: 14,
    durationFromChennaiHours: 0.4
  },
  "palavakkam-beach": {
    id: "p-palavakkam-beach",
    canonicalName: "Palavakkam Beach",
    name: "Palavakkam Beach",
    slug: "palavakkam-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9554,
    longitude: 80.2592,
    categories: ["beaches", "coastal"],
    primaryCategory: "beaches",
    tagline: "Well-maintained coastal beach with paved walkways, offering great open views for sunrise & sunset",
    description: "Palavakkam Beach is popular for its neat paved walking track, manicured seating benches, and wide open horizon views. Ideal for evening family strolls and watching sunrise over the Bay of Bengal.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "palavakkam", "palavakkam_beach", "paved_walkway", "ecr", "sunset"],
    highlights: [
      "Paved Promenade Walkway",
      "Panoramas for Sunrise & Sunset",
      "Family Recreation Benches",
      "Clean Sand Beach"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 8:00 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Palavakkam",
    distanceFromChennaiKm: 15,
    durationFromChennaiHours: 0.4
  },
  "neelankarai-beach": {
    id: "p-neelankarai-beach",
    canonicalName: "Neelankarai Beach",
    name: "Neelankarai Beach",
    slug: "neelankarai-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9440,
    longitude: 80.2580,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Peaceful, secluded beach that serves as an active nesting ground for endangered Olive Ridley sea turtles",
    description: "Neelankarai Beach is a pristine, peaceful coastal strip along ECR. Famous among nature lovers and marine conservationists as a key annual nesting ground for Olive Ridley sea turtles (Jan–April).",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation & TN Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "neelankarai", "neelankarai_beach", "turtle_nesting", "olive_ridley", "ecr"],
    highlights: [
      "Olive Ridley Sea Turtle Nesting Site",
      "Secluded Clean Sand Stretch",
      "Eco-Nature Conservation Shore",
      "Peaceful Horizon View"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 7:30 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Neelankarai",
    distanceFromChennaiKm: 16,
    durationFromChennaiHours: 0.45
  },
  "akkarai-beach": {
    id: "p-akkarai-beach",
    canonicalName: "Akkarai Beach",
    name: "Akkarai Beach",
    slug: "akkarai-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9280,
    longitude: 80.2560,
    categories: ["beaches", "coastal"],
    primaryCategory: "beaches",
    tagline: "Clean sands, minimal noise & manicured green approach pathways along the southern ECR shore",
    description: "Situated near the Akkarai junction on ECR, Akkarai Beach is renowned for its clean shoreline, landscaped lawn approaches, and quiet coastal air away from urban traffic.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "akkarai", "akkarai_beach", "ecr", "quiet_beach"],
    highlights: [
      "Manicured Green Approach Paths",
      "Low Noise & Traffic Atmosphere",
      "Clean Soft Golden Sands",
      "Secluded Coastal Vibe"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "4:30 PM - 7:30 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam / Akkarai",
    distanceFromChennaiKm: 17,
    durationFromChennaiHours: 0.45
  },
  "injambakkam-beach": {
    id: "p-injambakkam-beach",
    canonicalName: "Injambakkam Beach",
    name: "Injambakkam Beach",
    slug: "injambakkam-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9100,
    longitude: 80.2550,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Spacious, quiet beach ideal for solitary walks, located close to local seaside shrines & private estates",
    description: "Injambakkam Beach is a secluded coastal stretch featuring wide sandy shores, coastal palm trees, and gentle surf. Ideal for peaceful evening walks and watching coastal fishermen at work.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "injambakkam", "injambakkam_beach", "ecr", "quiet_walk"],
    highlights: [
      "Quiet Solitary Walk Trail",
      "Granite Pebble & Sand Shoreline",
      "Secluded ECR Coastal Retreat",
      "Traditional Catamaran Views"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 7:00 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam",
    distanceFromChennaiKm: 18,
    durationFromChennaiHours: 0.5
  },
  "uthandi-beach": {
    id: "p-uthandi-beach",
    canonicalName: "Uthandi Beach",
    name: "Uthandi Beach",
    slug: "uthandi-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8720,
    longitude: 80.2460,
    categories: ["beaches", "coastal", "nature"],
    primaryCategory: "beaches",
    tagline: "Pristine & private beach lane accessed primarily through a quiet residential neighborhood on ECR",
    description: "Located at the southern limit of Chennai district along ECR, Uthandi Beach is a pristine, hidden coastal avenue surrounded by quiet residential enclaves and coconut groves.",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "uthandi", "uthandi_beach", "ecr", "pristine_beach"],
    highlights: [
      "Pristine Residential Shoreline",
      "Ultra-Clean Uncrowded Sands",
      "Peaceful Sea Breeze Lane",
      "Secluded Coastal Haven"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:00 AM & 4:30 PM - 7:00 PM",
      duration: "1.5 hours",
      accessPermissions: "Open public beach."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Uthandi",
    distanceFromChennaiKm: 21,
    durationFromChennaiHours: 0.55
  },
  "vgp-golden-beach": {
    id: "p-vgp-golden-beach",
    canonicalName: "VGP Golden Beach",
    name: "VGP Golden Beach",
    slug: "vgp-golden-beach",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9145,
    longitude: 80.2522,
    categories: ["beaches", "coastal", "adventure", "tourist-places"],
    primaryCategory: "beaches",
    tagline: "Private, well-maintained beach integrated with VGP amusement park, safe & popular for family outings",
    description: "VGP Golden Beach in Injambakkam is one of Chennai's oldest managed beach park destinations. Integrated with VGP Universal Kingdom, featuring clean sands, sculptures, and safe family beach access.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "VGP Parks Official",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "vgp_golden_beach", "vgp", "injambakkam", "ecr", "amusement_park"],
    highlights: [
      "Managed Family Safe Beach",
      "Amusement & Water Park Access",
      "Statue & Fountain Gardens",
      "Clean Shoreline Facility"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "9:30 AM - 6:30 PM",
      duration: "Full day",
      accessPermissions: "Ticketed entry park."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam",
    distanceFromChennaiKm: 18,
    durationFromChennaiHours: 0.5
  },
  "muttukadu-beach": {
    id: "p-muttukadu-beach",
    canonicalName: "Muttukadu Beach & Backwaters",
    name: "Muttukadu Beach",
    slug: "muttukadu-beach",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8250,
    longitude: 80.2440,
    categories: ["beaches", "coastal", "adventure"],
    primaryCategory: "beaches",
    tagline: "Picturesque estuary where backwaters meet the sea, known for boating, windsurfing & watersports",
    description: "Situated 30 km south of Chennai on ECR, Muttukadu Beach sits where the Kovalam backwaters meet the Bay of Bengal. Features TTDC boat house with pedal boating, speedboats, and windsurfing.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TTDC & Chengalpattu District Admin",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "muttukadu", "muttukadu_beach", "backwaters", "boating", "ecr"],
    highlights: [
      "TTDC Backwater Boating House",
      "Estuary Confluence View",
      "Kayaking & Speedboat Rides",
      "Windsurfing Center"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "9:00 AM - 6:00 PM",
      duration: "2-3 hours",
      accessPermissions: "Ticketed boating activities."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Thiruporur",
    nearbyTown: "Muttukadu",
    distanceFromChennaiKm: 30,
    durationFromChennaiHours: 0.75
  },
  "mahabalipuram-beach": {
    id: "p-mahabalipuram-beach",
    canonicalName: "Mahabalipuram Beach (Mamallapuram)",
    name: "Mahabalipuram Beach",
    slug: "mahabalipuram-beach",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.6180,
    longitude: 80.1980,
    categories: ["beaches", "coastal", "heritage", "tourist-places"],
    primaryCategory: "beaches",
    tagline: "Historic coastal getaway combining golden beach sands with UNESCO World Heritage 7th-century Shore Temple",
    description: "Located 55 km south of Chennai, Mahabalipuram Beach offers a unique blend of coastal beauty and ancient Pallava rock-cut architecture. Backgrounded by the iconic 7th-century Shore Temple overlooking crashing ocean waves.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "Archaeological Survey of India & TN Tourism",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["beach", "coastal", "mahabalipuram", "mamallapuram", "shore_temple", "unesco", "heritage", "ecr"],
    highlights: [
      "UNESCO Shore Temple Backdrop",
      "Fresh Coastal Seafood Restaurants",
      "Handicrafts & Stone Carving Shops",
      "Surfing & Catamaran Sea Rides"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "Open 24/7 (Monuments 6:00 AM - 6:00 PM)",
      duration: "Half day / Full day",
      accessPermissions: "Free beach access; ASI ticket for Shore Temple."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Tirukalukundram",
    nearbyTown: "Mahabalipuram",
    distanceFromChennaiKm: 55,
    durationFromChennaiHours: 1.1
  },

  // --- CHENNAI SHOPPING & SHOPAHOLIC DESTINATIONS ---
  "t-nagar-shopping": {
    id: "p-t-nagar-shopping",
    canonicalName: "T. Nagar Shopping District",
    name: "T. Nagar",
    slug: "t-nagar",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0418,
    longitude: 80.2341,
    categories: ["shopping", "heritage", "tourist-places"],
    primaryCategory: "shopping",
    tagline: "South India's mega retail hub famous for Kanjivaram silk sarees, gold jewelry & street bazaars",
    description: "Thyagaraya Nagar (T. Nagar) is India's largest shopping district by revenue. Renowned for mega textile showrooms (Nalli, Pothys, RMKV), gold jewelry houses, and bustling street markets along Usman Road and Pondy Bazaar.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation & T. Nagar Merchants Association",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "street-shopping", "textiles", "sarees", "jewellery", "t_nagar", "budget-shopping", "fashion"],
    highlights: [
      "Usman Road Multi-Storey Silk Showrooms (Nalli, Pothys, Saravana)",
      "Panagal Park Gold & Diamond Jewelry Houses",
      "Pondy Bazaar Pedestrian Plaza",
      "Ranganathan Street Street Apparel"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "10:00 AM - 9:30 PM",
      duration: "3-4 hours",
      areaCentroid: { latitude: 13.0418, longitude: 80.2341 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "T. Nagar / Egmore",
    nearbyTown: "Central Chennai",
    distanceFromChennaiKm: 6,
    durationFromChennaiHours: 0.2
  },
  "sowcarpet-shopping": {
    id: "p-sowcarpet-shopping",
    canonicalName: "Sowcarpet Wholesale & Ethnic Bazaar",
    name: "Sowcarpet",
    slug: "sowcarpet",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0900,
    longitude: 80.2800,
    categories: ["shopping", "heritage", "food"],
    primaryCategory: "shopping",
    tagline: "Vibrant wholesale textile & lehenga bazaar famed for North Indian street food",
    description: "Located in North Chennai's George Town, Sowcarpet is a bustling commercial quarter famous for wholesale North Indian ethnic wear, bridal lehengas, dress materials, cosmetics, and legendary Marwari street food.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "wholesale", "ethnic-wear", "lehengas", "sowcarpet", "budget-shopping", "street-food"],
    highlights: [
      "Bridal Lehengas & Designer Anarkalis",
      "Mint Street Wholesale Fabrics & Cosmetics",
      "Jain Temple & Heritage Haveli Architecture",
      "Kakada Ramprasad & Anmol Lassi Food Trail"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "11:00 AM - 8:30 PM (Sundays mostly closed)",
      duration: "3 hours",
      areaCentroid: { latitude: 13.0900, longitude: 80.2800 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Fort Tondiarpet",
    nearbyTown: "George Town",
    distanceFromChennaiKm: 3,
    durationFromChennaiHours: 0.15
  },
  "besant-nagar-shopping": {
    id: "p-besant-nagar-shopping",
    canonicalName: "Besant Nagar Boutique & Beachside Shopping",
    name: "Besant Nagar Shopping Quarter",
    slug: "besant-nagar-shopping",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0002,
    longitude: 80.2668,
    categories: ["shopping", "tourist-places", "food"],
    primaryCategory: "shopping",
    tagline: "Relaxed coastal shopping filled with handicraft pop-ups, casual apparel & beach stalls",
    description: "Besant Nagar offers a relaxed, bohemian shopping experience combining artisan pop-up boutiques, cotton apparel stores, seaside accessory stalls, and coastal cafes along 6th Avenue and Elliot's Beach road.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "street-shopping", "boutiques", "casual-wear", "accessories", "besant_nagar"],
    highlights: [
      "Artisan Cotton Apparel & Handlooms",
      "Beachside Shell & Accessory Stalls",
      "Custom Handmade Footwear Shops",
      "6th Avenue Boutique Cafes"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "4:00 PM - 9:00 PM",
      duration: "2 hours",
      areaCentroid: { latitude: 13.0002, longitude: 80.2668 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Coastal",
    taluk: "Velachery",
    nearbyTown: "Besant Nagar",
    distanceFromChennaiKm: 11,
    durationFromChennaiHours: 0.3
  },
  "pondy-bazaar": {
    id: "p-pondy-bazaar",
    canonicalName: "Pondy Bazaar Street & Pedestrian Plaza",
    name: "Pondy Bazaar",
    slug: "pondy-bazaar",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0405,
    longitude: 80.2370,
    categories: ["shopping", "heritage", "tourist-places"],
    primaryCategory: "shopping",
    tagline: "Pedestrianized high-street bazaar famous for budget fashion, footwear, toys & accessories",
    description: "Situated in T. Nagar, Pondy Bazaar is Chennai's iconic high-street market. Featuring a modern tree-lined pedestrian plaza, multi-level vendor complexes, footwear shops, and trendy street fashion.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation Smart City Project",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "street-shopping", "footwear", "accessories", "budget-shopping", "pondy_bazaar", "t_nagar"],
    highlights: [
      "Pedestrian Plaza Walking Street",
      "Platform Footwear & Sandal Shops",
      "Trendy Handbags & Accessories Market",
      "Naidu Hall & Retail Outlets"
    ],
    placeType: "neighborhood",
    parentRegion: "p-t-nagar-shopping",
    metadata: {
      bestTime: "10:30 AM - 9:30 PM",
      duration: "2 hours",
      areaCentroid: { latitude: 13.0405, longitude: 80.2370 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "T. Nagar",
    nearbyTown: "T. Nagar",
    distanceFromChennaiKm: 6,
    durationFromChennaiHours: 0.2
  },
  "anna-nagar-shopping": {
    id: "p-anna-nagar-shopping",
    canonicalName: "Anna Nagar Fashion & Mall Precinct",
    name: "Anna Nagar Shopping District",
    slug: "anna-nagar-shopping",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0850,
    longitude: 80.2100,
    categories: ["shopping", "tourist-places"],
    primaryCategory: "shopping",
    tagline: "Upscale planned avenue shopping home to VR Chennai mall, designer boutiques & high streets",
    description: "Anna Nagar's 2nd Avenue and VR Chennai mega-mall create North-West Chennai's premier shopping strip. Offers international fashion brands, local designer boutiques, lifestyle stores, and gourmet eateries.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "fashion", "boutiques", "designer-wear", "vr_mall", "anna_nagar"],
    highlights: [
      "VR Chennai Flagship Mall",
      "2nd Avenue Boutique & Apparel Row",
      "Independent Designer Studios",
      "Gourmet Cafe & Bistro Strip"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "11:00 AM - 10:00 PM",
      duration: "3 hours",
      areaCentroid: { latitude: 13.0850, longitude: 80.2100 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Aminjikarai",
    nearbyTown: "Central Chennai",
    distanceFromChennaiKm: 7,
    durationFromChennaiHours: 0.25
  },
  "mylapore-shopping": {
    id: "p-mylapore-shopping",
    canonicalName: "Mylapore Traditional & Ethnic Shopping",
    name: "Mylapore Traditional Market",
    slug: "mylapore-shopping",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0339,
    longitude: 80.2687,
    categories: ["shopping", "heritage"],
    primaryCategory: "shopping",
    tagline: "Sacred mada street markets for Kanjivaram silk, temple jewelry, brassware & dance costumes",
    description: "Encircling Kapaleeshwarar Temple, Mylapore's mada streets are famed for authentic Kanjivaram silk sarees, temple brass lamps, dance costumes, fresh flower garlands, and traditional South Indian handicrafts.",
    image: "https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "Chennai Heritage Trust",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "traditional-shopping", "sarees", "jewellery", "ethnic-wear", "brassware", "mylapore"],
    highlights: [
      "Traditional Kanjivaram Silk Showrooms",
      "Temple Brass Lamps & Bronze Idols",
      "Bharatanatyam Costume & Jewelry Shops",
      "Fresh Jasmine Garland Stalls"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "9:30 AM - 1:00 PM & 4:30 PM - 8:30 PM",
      duration: "2 hours",
      areaCentroid: { latitude: 13.0339, longitude: 80.2687 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Mylapore",
    nearbyTown: "Mylapore",
    distanceFromChennaiKm: 5,
    durationFromChennaiHours: 0.2
  },
  "purasawalkam-shopping": {
    id: "p-purasawalkam-shopping",
    canonicalName: "Purasawalkam Family Textile & Jewelry Belt",
    name: "Purasawalkam Shopping Belt",
    slug: "purasawalkam-shopping",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0895,
    longitude: 80.2552,
    categories: ["shopping", "heritage"],
    primaryCategory: "shopping",
    tagline: "Historic central textile corridor for affordable family clothing, sarees & gold jewelry",
    description: "Purasawalkam High Road is a bustling central commercial market preferred by Chennai families for budget saree shopping, wedding apparel, footwear, gold jewelry, and everyday household goods.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "textiles", "sarees", "budget-shopping", "purasawalkam", "family-shopping"],
    highlights: [
      "Purasawalkam High Road Textile Showrooms",
      "Gold & Silver Jewelry Houses",
      "Family Ready-made Wear",
      "Footwear & Luggage Bazaars"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "10:30 AM - 9:00 PM",
      duration: "2-3 hours",
      areaCentroid: { latitude: 13.0895, longitude: 80.2552 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Purasawalkam",
    nearbyTown: "Central Chennai",
    distanceFromChennaiKm: 4,
    durationFromChennaiHours: 0.15
  },
  "ranganathan-street": {
    id: "p-ranganathan-street",
    canonicalName: "Ranganathan Street Budget Market",
    name: "Ranganathan Street",
    slug: "ranganathan-street",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0400,
    longitude: 80.2300,
    categories: ["shopping", "heritage"],
    primaryCategory: "shopping",
    tagline: "Legendary ultra-dense budget shopping street connecting Mambalam station to Usman Road",
    description: "Connecting Mambalam railway station to Usman Road in T. Nagar, Ranganathan Street is one of the densest retail streets in Asia. Packed with budget clothing stores, kitchenware, electronics, and street vendors.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "street-shopping", "budget-shopping", "ranganathan_street", "t_nagar", "textiles"],
    highlights: [
      "Ultra-Budget Ready-Made Apparel",
      "Mobile Accessories & Gadget Stalls",
      "Stainless Steel & Kitchen Utensils",
      "High-Energy Street Bazaar Atmosphere"
    ],
    placeType: "neighborhood",
    parentRegion: "p-t-nagar-shopping",
    metadata: {
      bestTime: "10:00 AM - 9:00 PM",
      duration: "1.5 hours",
      areaCentroid: { latitude: 13.0400, longitude: 80.2300 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "T. Nagar",
    nearbyTown: "T. Nagar",
    distanceFromChennaiKm: 6,
    durationFromChennaiHours: 0.2
  },
  "nungambakkam-shopping": {
    id: "p-nungambakkam-shopping",
    canonicalName: "Nungambakkam Luxury & Designer Boutique Hub",
    name: "Nungambakkam High Street",
    slug: "nungambakkam-shopping",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0604,
    longitude: 80.2407,
    categories: ["shopping", "food"],
    primaryCategory: "shopping",
    tagline: "High-end fashion district home to Khader Nawaz Khan Road designer boutiques & luxury retail",
    description: "Nungambakkam, particularly along Khader Nawaz Khan Road and Wallace Garden, is Chennai's luxury fashion hub featuring exclusive Indian designer couture, upscale jewelry houses, and international lifestyle brands.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["shopping", "boutiques", "designer-wear", "fashion", "luxury", "khader_nawaz_khan", "nungambakkam"],
    highlights: [
      "Khader Nawaz Khan Designer Couture Row",
      "Exclusive Indian Ethnic Fashion Houses",
      "Luxury Handbag & Accessories Outlets",
      "Chic High-End Coffee Bars"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "11:00 AM - 9:00 PM",
      duration: "2 hours",
      areaCentroid: { latitude: 13.0604, longitude: 80.2407 },
      experienceType: "shopping"
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Egmore / Nungambakkam",
    nearbyTown: "Central Chennai",
    distanceFromChennaiKm: 4,
    durationFromChennaiHours: 0.15
  },

  // --- CHENNAI NEIGHBORHOODS & CULTURAL EXPERIENCES ---
  "mylapore-neighborhood": {
    id: "p-mylapore-neighborhood",
    canonicalName: "Mylapore Cultural Neighborhood",
    name: "Mylapore",
    slug: "mylapore",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0339,
    longitude: 80.2687,
    categories: ["heritage", "food", "tourist-places"],
    primaryCategory: "heritage",
    tagline: "Historic cultural heartland of Chennai steeped in Dravidian temples, Carnatic music & filter coffee",
    description: "Predating modern Chennai by over 1,500 years, Mylapore is a historic neighborhood famed for Kapaleeshwarar Temple, bustling mada streets selling traditional brassware, classic South Indian messes, and December Margazhi music sabhas.",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Mylapore_Theppam_Festival.jpg",
    verified: true,
    source: "Chennai Heritage Trust",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["mylapore", "chennai", "heritage", "carnatic_music", "filter_coffee", "temple_town"],
    highlights: [
      "Four Sacred Mada Streets",
      "Kapaleeshwarar Temple Tank",
      "Traditional Brassware & Flower Markets",
      "Historic Filter Coffee Messes"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "Morning (6 AM - 10 AM) & Evening (4 PM - 8 PM)",
      duration: "3-4 hours",
      areaCentroid: { latitude: 13.0339, longitude: 80.2687 }
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Mylapore",
    nearbyTown: "Central Chennai",
    distanceFromChennaiKm: 5,
    durationFromChennaiHours: 0.2
  },
  "kapaleeshwarar-temple": {
    id: "p-kapaleeshwarar-temple",
    canonicalName: "Kapaleeshwarar Temple",
    name: "Kapaleeshwarar Temple",
    slug: "kapaleeshwarar-temple",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0335,
    longitude: 80.2697,
    categories: ["temples", "heritage"],
    primaryCategory: "temples",
    tagline: "7th-century Dravidian gopuram architectural marvel dedicated to Lord Shiva",
    description: "Built in classic 7th-century Dravidian architecture, Kapaleeshwarar Temple is dedicated to Lord Shiva (Kapaleeshwarar) and Parvati (Karpagambal). Features a majestic 120-ft rainbow gopuram and a sacred temple tank.",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Kapaleeswarar1.jpg",
    verified: true,
    source: "HR&CE Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["kapaleeshwarar", "mylapore", "shiva_temple", "gopuram", "dravidian_architecture"],
    highlights: [
      "120-ft Rainbow Sculpted Gopuram",
      "Temple Tank & Sacred Courtyard",
      "Karpagambal Peacock Shrine",
      "Annual Panguni Peruvizha Chariot Festival"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "6:00 AM - 12:00 PM & 4:00 PM - 9:00 PM",
      duration: "1-2 hours",
      accessPermissions: "Traditional modest dress code enforced."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Mylapore",
    nearbyTown: "Mylapore",
    distanceFromChennaiKm: 5,
    durationFromChennaiHours: 0.2
  },
  "south-indian-breakfast-experience": {
    id: "exp-south-indian-breakfast-mylapore",
    canonicalName: "South Indian Breakfast Experience (Mylapore)",
    name: "South Indian Breakfast Experience",
    slug: "south-indian-breakfast-experience",
    entityType: "EXPERIENCE",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0339,
    longitude: 80.2687,
    categories: ["food", "heritage"],
    primaryCategory: "food",
    tagline: "Authentic morning trail savouring steaming Ghee Podi Idli, Vadai & Degree Coffee",
    description: "Curated culinary exploration through Mylapore's legendary heritage messes. Sample hot crispy medu vadai, fluffy idlis dipped in spicy sambar, ghee roast dosai, and authentic brass-tumbler degree filter coffee.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "ExplorerTN Food Trail",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["breakfast", "mylapore", "filter_coffee", "idli_sambar", "food_trail", "chennai_food"],
    highlights: [
      "Steaming Ghee Podi Idli & Coconut Chutney",
      "Crispy Medu Vadai with Sambar",
      "Traditional Brass Tumbler Filter Coffee Walk",
      "Heritage Mess Atmosphere"
    ],
    placeType: "experience",
    metadata: {
      bestTime: "7:00 AM - 10:30 AM",
      duration: "1.5 hours",
      areaCentroid: { latitude: 13.0339, longitude: 80.2687 }
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Mylapore",
    nearbyTown: "Mylapore",
    distanceFromChennaiKm: 5,
    durationFromChennaiHours: 0.2
  },
  "south-indian-lunch-experience": {
    id: "exp-south-indian-lunch-mylapore",
    canonicalName: "South Indian Banana Leaf Lunch Experience (Mylapore)",
    name: "South Indian Lunch Experience",
    slug: "south-indian-lunch-experience",
    entityType: "EXPERIENCE",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0345,
    longitude: 80.2690,
    categories: ["food", "heritage"],
    primaryCategory: "food",
    tagline: "Elaborate traditional 14-item Sappadu served on fresh plantain leaf",
    description: "Authentic Tamil meal experience served on a traditional banana leaf featuring aromatic Ponni rice, Kovakkai Poriyal, Vathakuzhambu, Paruppu with Ghee, Rasam, Moru, and Sweet Payasam.",
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "ExplorerTN Food Trail",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["banana_leaf_lunch", "sappadu", "mylapore", "vathakuzhambu", "rasam", "chennai_food"],
    highlights: [
      "Traditional Banana Leaf Presentation",
      "Rich Vathakuzhambu & Pepper Rasam",
      "Crispy Appalam & Homemade Pickles",
      "Warm Payasam Dessert Finish"
    ],
    placeType: "experience",
    metadata: {
      bestTime: "12:30 PM - 3:00 PM",
      duration: "1 hour",
      areaCentroid: { latitude: 13.0345, longitude: 80.2690 }
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Mylapore",
    nearbyTown: "Mylapore",
    distanceFromChennaiKm: 5,
    durationFromChennaiHours: 0.2
  },
  "dakshinachitra": {
    id: "p-dakshinachitra-museum",
    canonicalName: "DakshinaChitra Heritage Museum",
    name: "DakshinaChitra",
    slug: "dakshinachitra",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8239,
    longitude: 80.2415,
    categories: ["museums", "heritage", "tourist-places"],
    primaryCategory: "museums",
    tagline: "Living heritage museum showcasing 18 authentic reconstructed South Indian houses",
    description: "Located in Muttukadu along the East Coast Road, DakshinaChitra is a living museum displaying 18 authentic historic houses purchased, dismantled, and reconstructed from Tamil Nadu, Kerala, Karnataka, and Andhra Pradesh.",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "Madras Craft Foundation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["dakshinachitra", "muttukadu", "ecr", "heritage_museum", "traditional_houses", "crafts"],
    highlights: [
      "Reconstructed Chettinad Mansion",
      "Kerala Syrian Christian Timber House",
      "Live Artisan Workshops (Pottery, Weaving)",
      "South Indian Folk Dance Performances"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "10:00 AM - 6:00 PM (Closed Tuesdays)",
      duration: "3 hours",
      accessPermissions: "Ticketed entry. Camera fee applies."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Thiruporur",
    nearbyTown: "Muttukadu / ECR (25 km from Chennai)",
    distanceFromChennaiKm: 25,
    durationFromChennaiHours: 0.75
  },
  "nungambakkam-neighborhood": {
    id: "p-nungambakkam-neighborhood",
    canonicalName: "Nungambakkam Commercial & Dining Hub",
    name: "Nungambakkam",
    slug: "nungambakkam",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0604,
    longitude: 80.2407,
    categories: ["food", "heritage", "tourist-places"],
    primaryCategory: "food",
    tagline: "Upscale central neighborhood featuring global dining, art galleries & Khader Nawaz Khan Road",
    description: "Nungambakkam is one of Chennai's premier central districts, blending colonial heritage landmarks (Valluvar Kottam, Alliance Française) with modern luxury shopping, art galleries, and Khader Nawaz Khan Road fine dining.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["nungambakkam", "chennai", "shopping", "fine_dining", "khader_nawaz_khan", "valluvar_kottam"],
    highlights: [
      "Valluvar Kottam Chariot Monument",
      "Khader Nawaz Khan High Street Dining",
      "Apparao Contemporary Art Galleries",
      "Lush Connemara Library Proximity"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "11:00 AM - 10:00 PM",
      duration: "2-3 hours",
      areaCentroid: { latitude: 13.0604, longitude: 80.2407 }
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Egmore / Nungambakkam",
    nearbyTown: "Central Chennai",
    distanceFromChennaiKm: 4,
    durationFromChennaiHours: 0.15
  },
  "theosophical-society": {
    id: "p-theosophical-society",
    canonicalName: "Theosophical Society Estate & Gardens",
    name: "Theosophical Society",
    slug: "theosophical-society",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0108,
    longitude: 80.2573,
    categories: ["nature", "heritage"],
    primaryCategory: "nature",
    tagline: "260-acre green sanctuary along Adyar river featuring 450-year-old Great Banyan Tree",
    description: "Established in 1882 by Helena Blavatsky and Henry Steel Olcott, the International Headquarters of the Theosophical Society spans 260 acres of serene woodland along the Adyar River.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Theosophical Society International HQ",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["theosophical_society", "adyar", "banyan_tree", "nature_sanctuary", "heritage_estate"],
    highlights: [
      "Historic 450-Year-Old Adyar Banyan Tree",
      "Adyar River Forest Canopy Walk",
      "Interfaith Shrines (Church, Mosque, Temple, Buddhist Shrine)",
      "Adyar Library & Research Centre"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "8:30 AM - 10:00 AM & 3:00 PM - 5:00 PM (Closed Sundays)",
      duration: "1.5 hours",
      accessPermissions: "Quiet entry allowed during public visiting hours."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Coastal",
    taluk: "Velachery",
    nearbyTown: "Adyar",
    distanceFromChennaiKm: 9,
    durationFromChennaiHours: 0.25
  },
  "adyar-neighborhood": {
    id: "p-adyar-neighborhood",
    canonicalName: "Adyar Estuary & Cultural District",
    name: "Adyar",
    slug: "adyar",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0067,
    longitude: 80.2571,
    categories: ["heritage", "food", "nature"],
    primaryCategory: "heritage",
    tagline: "Leafy southern district home to Kalakshetra Foundation, eco-parks & famous sweets",
    description: "Bordered by the Adyar River and the Bay of Bengal, Adyar is a green cultural neighborhood known for Kalakshetra Foundation (Bharatanatyam school), Adyar Poonga eco-park, and classic eateries.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["adyar", "chennai", "kalakshetra", "adyar_poonga", "sweets", "estuary"],
    highlights: [
      "Kalakshetra Foundation Arts Academy",
      "Tholkappia Poonga Eco-Restoration Park",
      "Adyar Ananda Bhavan Flagship",
      "Gandhi Nagar Tree-Lined Avenues"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "Morning & Evening",
      duration: "2 hours",
      areaCentroid: { latitude: 13.0067, longitude: 80.2571 }
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Coastal",
    taluk: "Velachery",
    nearbyTown: "South Chennai",
    distanceFromChennaiKm: 9,
    durationFromChennaiHours: 0.25
  },
  "madras-crocodile-bank": {
    id: "p-madras-crocodile-bank",
    canonicalName: "Madras Crocodile Bank Trust & Centre for Herpetology",
    name: "Madras Crocodile Bank",
    slug: "madras-crocodile-bank",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.7536,
    longitude: 80.2223,
    categories: ["wildlife", "tourist-places"],
    primaryCategory: "wildlife",
    tagline: "Pioneering reptile zoo & captive breeding centre housing over 2,000 crocodiles",
    description: "Founded by Romulus Whitaker in 1976 along the East Coast Road (Vadanemmeli), the Croc Bank is a world-renowned reptile conservation sanctuary safeguarding endangered mugger, saltwater, and gharial crocodiles.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Madras Crocodile Bank Trust",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["crocodile_bank", "croc_bank", "ecr", "vadanemmeli", "romulus_whitaker", "reptiles"],
    highlights: [
      "Massive Marsh Crocodile & Gharial Ponds",
      "Jaws III — Giant Saltwater Crocodile",
      "Night Safari Reptile Experience",
      "Underwater Crocodile Viewing Glass"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "9:00 AM - 5:30 PM (Closed Mondays). Night safari 7 PM - 8:30 PM.",
      duration: "2 hours",
      accessPermissions: "Ticketed conservation entry."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Thiruporur",
    nearbyTown: "Vadanemmeli / ECR (40 km from Chennai)",
    distanceFromChennaiKm: 40,
    durationFromChennaiHours: 1.0
  },
  "ecr-region": {
    id: "p-ecr-coastal-corridor",
    canonicalName: "East Coast Road (ECR) Scenic Corridor",
    name: "ECR (East Coast Road)",
    slug: "ecr",
    entityType: "REGION",
    district: "Chennai & Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8500,
    longitude: 80.2450,
    categories: ["coastal", "beaches", "tourist-places"],
    primaryCategory: "coastal",
    tagline: "Scenic two-lane coastal highway connecting Chennai to Mahabalipuram & Puducherry",
    description: "East Coast Road (SH-49) is a famed coastal highway hugging the Bay of Bengal coastline. Lined with quiet beach resorts, art villages, amusement parks, seafood restaurants, and heritage stops.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Road Development Company",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["ecr", "east_coast_road", "scenic_drive", "coastal_highway", "resorts", "drive"],
    highlights: [
      "Bay of Bengal Ocean Drive Views",
      "Muttukadu Backwater Boating",
      "Beachside Resorts & Seafood Shacks",
      "Gateway to UNESCO Mahabalipuram"
    ],
    placeType: "region",
    metadata: {
      bestTime: "Early Morning Drive & Sunset Hours",
      duration: "Half day / Weekend drive",
      areaCentroid: { latitude: 12.8500, longitude: 80.2450 }
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam to Mahabalipuram",
    distanceFromChennaiKm: 20,
    durationFromChennaiHours: 0.5
  },
  "vgp-universal-kingdom": {
    id: "p-vgp-universal-kingdom",
    canonicalName: "VGP Universal Kingdom & Aqua Kingdom",
    name: "VGP Universal Kingdom",
    slug: "vgp-universal-kingdom",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9158,
    longitude: 80.2520,
    categories: ["adventure", "tourist-places"],
    primaryCategory: "adventure",
    tagline: "Chennai's premier seaside amusement & water theme park at Injambakkam",
    description: "Located along ECR in Injambakkam, VGP Universal Kingdom is an iconic 45-acre amusement park established in 1975 featuring over 50 thrilling rides, a massive wave pool at VGP Aqua Kingdom, and VGP Marine Kingdom aquarium.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "VGP Parks Official",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["vgp", "universal_kingdom", "injambakkam", "ecr", "amusement_park", "water_park"],
    highlights: [
      "VGP Marine Kingdom Walkthrough Aquarium",
      "Roller Coasters & Ferris Wheel",
      "VGP Aqua Kingdom Wave Pool",
      "Private Golden Beach Access"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "9:30 AM - 6:30 PM",
      duration: "Full day",
      accessPermissions: "Ticketed entry pass."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam",
    distanceFromChennaiKm: 18,
    durationFromChennaiHours: 0.5
  },
  "anna-nagar-neighborhood": {
    id: "p-anna-nagar-neighborhood",
    canonicalName: "Anna Nagar Modern Township & Commercial Hub",
    name: "Anna Nagar",
    slug: "anna-nagar",
    entityType: "NEIGHBORHOOD",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0850,
    longitude: 80.2100,
    categories: ["food", "tourist-places"],
    primaryCategory: "food",
    tagline: "Planned grid township featuring Anna Tower Park, vibrant cafes & high-street shopping",
    description: "Developed for the 1968 World Tamil Conference, Anna Nagar is a premier planned township in North-West Chennai. Known for its symmetrical avenues, 135-ft Anna Tower Park, VR Chennai Mall, and trendy food joints.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["anna_nagar", "chennai", "anna_tower", "vr_mall", "shopping", "food_hub", "neighborhood"],
    highlights: [
      "135-ft Iconic Anna Tower & Park",
      "VR Chennai Shopping & Entertainment Center",
      "2nd Avenue High-Street Cafe Strip",
      "Grid-Planned Avenue Layout"
    ],
    placeType: "neighborhood",
    metadata: {
      bestTime: "Morning Park Walks & Evening Dining (4 PM - 10 PM)",
      duration: "2-3 hours",
      areaCentroid: { latitude: 13.0850, longitude: 80.2100 }
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Aminjikarai",
    nearbyTown: "Central Chennai",
    distanceFromChennaiKm: 7,
    durationFromChennaiHours: 0.25
  },
  "knk-road": {
    id: "p-knk-road",
    canonicalName: "Khader Nawaz Khan Road (KNK Road)",
    name: "KNK Road (Khader Nawaz Khan Road)",
    slug: "knk-road",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0607,
    longitude: 80.2462,
    categories: ["shopping", "food", "tourist-places"],
    primaryCategory: "shopping",
    tagline: "Chennai's premier luxury high-street promenade in Nungambakkam featuring elite fashion boutiques & fine dining",
    description: "Khader Nawaz Khan Road (KNK Road) in Nungambakkam is Chennai's signature upscale fashion and lifestyle Boulevard. Spanning pedestrian-friendly tree-lined sidewalks, it hosts luxury international brands, designer haute couture, artisan bakeries, and gourmet international restaurants.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Greater Chennai Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["knk_road", "khader_nawaz_khan_road", "nungambakkam", "luxury_shopping", "boutiques", "fine_dining", "high_street", "chennai"],
    highlights: [
      "Luxury Fashion Boutiques & Designer Apparel",
      "Gourmet Bakeries & Trendy Cafes",
      "Upscale Fine Dining Restaurants",
      "Pedestrian-Friendly High-Street Promenade"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "11:00 AM - 10:30 PM",
      duration: "2-3 hours",
      accessPermissions: "Open high-street access."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Egmore-Nungambakkam",
    nearbyTown: "Nungambakkam",
    distanceFromChennaiKm: 4,
    durationFromChennaiHours: 0.15
  },
  "phoenix-marketcity-velachery": {
    id: "p-phoenix-marketcity-velachery",
    canonicalName: "Phoenix Marketcity Velachery",
    name: "Phoenix Marketcity Velachery",
    slug: "phoenix-marketcity-velachery",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9918,
    longitude: 80.2170,
    categories: ["shopping", "food", "entertainment", "tourist-places"],
    primaryCategory: "shopping",
    tagline: "Chennai's flagship mega retail & entertainment destination with IMAX, Palladium luxury mall, and indoor play zones",
    description: "Spanning over 1 million square feet in Velachery, Phoenix Marketcity is one of South India's premier shopping and entertainment complexes. Featuring over 300 international brands, the IMAX Luxe multiplex, Palladium luxury wing, Fun City gaming, and a massive multi-cuisine food court.",
    image: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Phoenix Mills Official",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["phoenix_marketcity", "velachery", "palladium", "imax", "shopping_mall", "gaming_zone", "food_court", "chennai"],
    highlights: [
      "Palladium Luxury Retail Mall Wing",
      "Luxe IMAX 11-Screen Multiplex",
      "Fun City & Indoor Entertainment Zones",
      "Global Multi-Cuisine Dining Courtyard"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "10:30 AM - 10:00 PM",
      duration: "3-4 hours",
      accessPermissions: "Free mall entry; ticketed cinema & gaming zones."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Urban",
    taluk: "Velachery",
    nearbyTown: "Velachery",
    distanceFromChennaiKm: 12,
    durationFromChennaiHours: 0.3
  },
  "breakthru-college-road": {
    id: "p-breakthru-college-road",
    canonicalName: "Breakthru - The Real Escape Room (College Road)",
    name: "Breakthru Escape Room",
    slug: "breakthru-college-road",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0618,
    longitude: 80.2472,
    categories: ["adventure", "entertainment", "tourist-places"],
    primaryCategory: "adventure",
    tagline: "Immersive 60-minute real-life escape room adventure center on College Road, Nungambakkam",
    description: "Located on College Road in Nungambakkam, Breakthru is Chennai's top-rated real-life escape game venue. Groups of 2–8 players are locked in themed rooms like 'The Crypt', 'Asylum Aftermath', 'Grand Theft Mobsters', and 'GBay Breakout' to solve puzzles and unlock clues within 60 minutes.",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Breakthru Escape Official",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["breakthru", "escape_room", "college_road", "nungambakkam", "gaming", "puzzles", "adventure", "team_building"],
    highlights: [
      "4 Immersive Themed Escape Chambers (Horror, Heist, Sci-Fi)",
      "60-Minute Mind-Bending Mystery Puzzles",
      "Private Interactive Group Challenges",
      "Central Nungambakkam College Road Location"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "11:00 AM - 9:30 PM",
      duration: "1.5 hours",
      accessPermissions: "Prior booking required. Ticketed sessions (~₹650/person)."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Egmore-Nungambakkam",
    nearbyTown: "Nungambakkam / Thousand Lights",
    distanceFromChennaiKm: 4.5,
    durationFromChennaiHours: 0.15
  },
  "madras-international-karting-arena": {
    id: "p-madras-international-karting-arena",
    canonicalName: "Madras International Karting Arena (MIKA)",
    name: "Madras International Karting Arena",
    slug: "madras-international-karting-arena",
    entityType: "POI",
    district: "Kanchipuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0025,
    longitude: 79.9858,
    categories: ["adventure", "sports", "tourist-places"],
    primaryCategory: "adventure",
    tagline: "World-class CIK-FIA standard international karting circuit designed by Driven International at Irungattukottai",
    description: "Situated within the iconic Madras International Circuit (MIC) grounds in Irungattukottai near Sriperumbudur, MIKA is India's premier CIK-FIA standard go-karting facility. Designed by world-renowned track designers Driven International, it features a 1.2 km floodlit tarmac circuit, high-performance twin-engine rental karts, and technical turns.",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Madras Motor Sports Club",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["mika", "madras_international_karting_arena", "irungattukottai", "sriperumbudur", "go_karting", "motorsports", "circuit", "racing"],
    highlights: [
      "1.2 km CIK-FIA International Standard Circuit",
      "Night Karting with High-Intensity Floodlights",
      "Sodi RX8 & High-Performance Karts",
      "Adjacent to Historic Madras International Circuit Track"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "2:00 PM - 10:00 PM (Best for Evening Floodlit Racing)",
      duration: "2-3 hours",
      accessPermissions: "Ticketed sessions with mandatory safety gear provided."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "West Chennai Industrial Corridor",
    taluk: "Sriperumbudur",
    nearbyTown: "Irungattukottai / Sriperumbudur",
    distanceFromChennaiKm: 35,
    durationFromChennaiHours: 0.75
  },
  "sriperumbudur": {
    id: "p-sriperumbudur",
    canonicalName: "Sriperumbudur (Heritage, Temples & Industrial Hub)",
    name: "Sriperumbudur",
    slug: "sriperumbudur",
    entityType: "CITY",
    district: "Kanchipuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9667,
    longitude: 79.9450,
    categories: ["culture", "heritage", "tourist-places"],
    primaryCategory: "heritage",
    tagline: "Historic birthland of Vaishnavite philosopher Sri Ramanuja & home to Rajiv Gandhi Memorial",
    description: "Located 40 km west of Chennai along NH4, Sriperumbudur is a historic town renowned as the 1017 CE birthplace of Sri Ramanujacharya (Sri Adikesava Perumal Temple) and the site of the solemn Rajiv Gandhi National Memorial. Today, it also serves as Tamil Nadu's premier automotive & manufacturing industrial corridor.",
    image: "https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "Kanchipuram District Administration",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["sriperumbudur", "ramanuja_temple", "rajiv_gandhi_memorial", "kanchipuram", "heritage", "history", "temples"],
    highlights: [
      "Sri Adikesava Perumal Temple (Birthplace of Sri Ramanujar)",
      "Rajiv Gandhi National Memorial & Serene Gardens",
      "Vallakottai Murugan Temple (Tallest Murugan Idol nearby)",
      "Gateway to Motorsports at Madras International Circuit"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "6:00 AM - 12:00 PM & 4:00 PM - 8:00 PM",
      duration: "Half day (3-4 hours)",
      accessPermissions: "Free public entry for temples and memorial."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "West Chennai Industrial Corridor",
    taluk: "Sriperumbudur",
    nearbyTown: "Sriperumbudur",
    distanceFromChennaiKm: 40,
    durationFromChennaiHours: 0.8
  },
  "vgp-snow-kingdom": {
    id: "p-vgp-snow-kingdom",
    canonicalName: "VGP Snow Kingdom (East Coast Road)",
    name: "VGP Snow Kingdom",
    slug: "vgp-snow-kingdom",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9131,
    longitude: 80.2511,
    categories: ["adventure", "entertainment", "tourist-places"],
    primaryCategory: "adventure",
    tagline: "India's largest indoor snow theme park with sub-zero temperatures, snow slides & igloos at Injambakkam",
    description: "Situated along ECR next to VGP Universal Kingdom in Injambakkam, VGP Snow Kingdom is a massive indoor winter wonderland maintained at a constant -8°C. Visitors don provided thermal jackets and boots to enjoy real artificial snowfall, snow mountain slides, snowball fights, igloos, and ice sculptures.",
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "VGP Parks Official",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["vgp_snow_kingdom", "snow_park", "ecr", "injambakkam", "sub_zero", "family_entertainment", "snow_slides", "chennai"],
    highlights: [
      "-8°C Indoor Sub-Zero Snow Zone",
      "Snow Tubing & Steep Mountain Slides",
      "Real Artificial Snowfall Sessions",
      "Life-size Snow Igloos & Ice Statues"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "10:00 AM - 8:00 PM (45-minute cold room sessions)",
      duration: "2 hours",
      accessPermissions: "Ticketed entry (includes winter coat, boots & gloves)."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam",
    distanceFromChennaiKm: 18,
    durationFromChennaiHours: 0.5
  },
  "glow-garden-mahabalipuram": {
    id: "p-glow-garden-mahabalipuram",
    canonicalName: "Mahab's Glow Garden (Mahabalipuram)",
    name: "Mahab's Glow Garden",
    slug: "glow-garden-mahabalipuram",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.6208,
    longitude: 80.1945,
    categories: ["entertainment", "tourist-places", "coastal"],
    primaryCategory: "entertainment",
    tagline: "Magical night-time illuminated park inside Maragatha Poonga featuring giant LED light sculptures",
    description: "Located on East Raja Street inside TTDC Maragatha Poonga in Mamallapuram (Mahabalipuram), Mahab's Glow Garden is a mesmerizing day-to-night theme park. It comes alive after dusk with thousands of color-changing LED installations depicting wildlife, sea creatures, fantasy tunnels, and children's amusement rides.",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TTDC Maragatha Poonga",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["glow_garden", "mahabalipuram", "mamallapuram", "maragatha_poonga", "led_art", "night_park", "light_show", "ecr"],
    highlights: [
      "Illuminated LED Animal & Floral Sculptures",
      "Interactive Neon Light Tunnels",
      "Amusement Rides & Toy Train for Children",
      "Night Leisure Park Experience on ECR"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "6:00 PM - 10:00 PM (Best for Evening Glow)",
      duration: "2 hours",
      accessPermissions: "Ticketed entry park."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Tirukalukundram",
    nearbyTown: "Mahabalipuram",
    distanceFromChennaiKm: 55,
    durationFromChennaiHours: 1.1
  },
  "the-beach-terrace-ecr": {
    id: "p-the-beach-terrace-ecr",
    canonicalName: "The Beach Terrace (ECR Oceanfront Santorini Resto-Bar)",
    name: "The Beach Terrace ECR",
    slug: "the-beach-terrace-ecr",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8945,
    longitude: 80.2525,
    categories: ["food", "coastal", "tourist-places"],
    primaryCategory: "food",
    tagline: "Santorini-inspired oceanfront open-air terrace resto-bar & dining venue at Injambakkam ECR",
    description: "Nestled along the beach front at Injambakkam, East Coast Road, The Beach Terrace is an enchanting Aegean-themed open-air destination. Featuring whitewashed Greek architecture, ocean-view rooftop seating, sea breeze, artisanal cocktails, and live seafood grills.",
    image: "https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "VGP Heritage Venues",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["the_beach_terrace", "beach_terrace_ecr", "injambakkam", "ecr", "santorini_vibe", "oceanfront_dining", "resto_bar", "sea_view"],
    highlights: [
      "Whitewashed Santorini Architecture & Ocean Views",
      "Open-Air Beachfront Rooftop Seating",
      "Coastal Seafood Grills & Artisanal Cocktails",
      "Sunset Golden Hour Vibe"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:00 PM - 11:30 PM (Sunset & Dinner)",
      duration: "2-3 hours",
      accessPermissions: "Table reservation recommended."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Injambakkam / Neelankarai",
    distanceFromChennaiKm: 19,
    durationFromChennaiHours: 0.5
  },
  "go-xtreme-adventures": {
    id: "p-go-xtreme-adventures",
    canonicalName: "Go Xtreme Paintball & Adventure Zone (Sholinganallur / Uthandi ECR)",
    name: "Go Xtreme Adventures",
    slug: "go-xtreme-adventures",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8700,
    longitude: 80.2400,
    categories: ["adventure", "sports", "tourist-places"],
    primaryCategory: "adventure",
    tagline: "Outdoor adrenaline park featuring tactical paintball arena, archery, zorbing & obstacle courses",
    description: "Located along the ECR corridor near Uthandi / Sholinganallur, Go Xtreme Adventures is Chennai's top outdoor tactical gaming arena. Features an authentic speedball/woodball paintball field, archery target shooting, human foosball, body zorbing, and team bonding challenge arenas.",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Go Xtreme Adventures Official",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["go_xtreme", "paintball", "sholinganallur", "uthandi", "ecr", "adventure_park", "zorbing", "archery"],
    highlights: [
      "Tactical Outdoor Paintball Battlefield",
      "Archery Target Range & Air Rifle Shooting",
      "Body Zorbing & Human Foosball",
      "Corporate Team Building & Thrill Games"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "10:00 AM - 7:30 PM",
      duration: "2-3 hours",
      accessPermissions: "Ticketed per activity or combo package."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "ECR Coastal Corridor",
    taluk: "Sholinganallur",
    nearbyTown: "Sholinganallur / Uthandi",
    distanceFromChennaiKm: 22,
    durationFromChennaiHours: 0.55
  },
  "eco-park-chetpet": {
    id: "p-eco-park-chetpet",
    canonicalName: "Chetpet Eco-Park & Sport Fishing Lake",
    name: "Chetpet Eco-Park",
    slug: "eco-park-chetpet",
    entityType: "POI",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0742,
    longitude: 80.2425,
    categories: ["nature", "waterbodies", "tourist-places"],
    primaryCategory: "nature",
    tagline: "16-acre urban oasis lake featuring pedal boating, sport fishing, elevated walkway & seafood restaurant",
    description: "Situated in central Chennai on Poonamallee High Road, Chetpet Eco-Park is a restored 16-acre urban waterbody maintained by the TN Department of Fisheries. Offers angling and sport fishing, pedal boating, a 1.5 km tree-shaded walking track, children's park, and an open-air seafood dining plaza.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Department of Fisheries",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T19:00:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["chetpet_eco_park", "chetpet_lake", "sport_fishing", "boating", "walking_track", "chetpet", "urban_park", "chennai"],
    highlights: [
      "16-Acre Restored Urban Lake & Wetland",
      "Sport Fishing & Angling Facilities",
      "Pedal & Motorized Boating Rides",
      "1.5 km Lakeside Promenade & Seafood Plaza"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "6:00 AM - 9:00 AM & 4:00 PM - 7:30 PM",
      duration: "2 hours",
      accessPermissions: "Nominal entry fee (₹25); separate tickets for boating & fishing."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Egmore",
    nearbyTown: "Chetpet / Kilpauk",
    distanceFromChennaiKm: 3,
    durationFromChennaiHours: 0.1
  }
};
