import { ExplorerPlace } from "./canonical-places";

export const COIMBATORE_REGIONAL_PLACES: Record<string, ExplorerPlace> = {
  "parambikulam": {
    id: "p-parambikulam",
    canonicalName: "Parambikulam Tiger Reserve",
    name: "Parambikulam Tiger Reserve",
    slug: "parambikulam",
    entityType: "POI",
    district: "Palakkad",
    state: "Kerala",
    country: "India",
    latitude: 10.4287,
    longitude: 76.7797,
    categories: ["wildlife", "trekking", "tourist-places"],
    primaryCategory: "wildlife",
    tagline: "Pristine Western Ghats eco-reserve with wild Asian elephants & Kannimara Teak",
    description: "Spanning 643 sq km in Palakkad district bordering Anamalai, Parambikulam is a premier tiger reserve known for the world's oldest living teak tree (Kannimara Teak, ~450 yrs), bamboo rafting on Parambikulam Lake, and guided tribal eco-tourism.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Kerala Forest Department",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["wildlife", "parambikulam", "palakkad", "kerala", "tiger_reserve", "eco_tourism", "bamboo_rafting"],
    highlights: [
      "Kannimara Teak Tree (450+ yrs)",
      "Bamboo Rafting on Parambikulam Reservoir",
      "Guarded Jungle Safari",
      "Tribal Eco-Tourism Walk"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to March",
      duration: "Full day / 1 night",
      accessPermissions: "Advance permit booking via Kerala Forest Dept required. Entry via Sethumadai gate.",
      forestPermitRequired: true,
      roadCondition: "Good till Sethumadai; forest roads inside reserve."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Pollachi & Anamalai Region",
    taluk: "Chittur",
    nearbyTown: "Pollachi (38 km)",
    distanceFromCoimbatoreKm: 96,
    durationFromCoimbatoreHours: 2.5
  },
  "coonoor": {
    id: "p-coonoor",
    canonicalName: "Coonoor Hill Station",
    name: "Coonoor",
    slug: "coonoor",
    entityType: "HILL",
    district: "The Nilgiris",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.3530,
    longitude: 76.7959,
    categories: ["hills", "tourist-places", "heritage"],
    primaryCategory: "hills",
    tagline: "Tranquil Nilgiri hill station celebrated for Sim's Park & panoramic tea slopes",
    description: "Nestled at 1,850m elevation in the Nilgiri Hills, Coonoor is renowned for its lush green tea estates, Victorian botanical collections at Sim's Park, and dramatic cliff viewpoints at Dolphin's Nose and Lamb's Rock.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Tamil Nadu Tourism",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["coonoor", "nilgiris", "hills", "tea_estates", "sims_park", "toy_train"],
    highlights: [
      "Sim's Park Botanical Collection",
      "Dolphin's Nose Cliff View",
      "Lamb's Rock Viewpoint",
      "Nilgiri Mountain Railway Toy Train"
    ],
    placeType: "town",
    metadata: {
      bestTime: "September to May",
      duration: "1-2 days",
      accessPermissions: "Open public access. Toy train requires IRCTC reservation.",
      roadCondition: "Good tarmac via Mettupalayam-Coonoor Ghat Road."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Nilgiris",
    taluk: "Coonoor",
    nearbyTown: "Coonoor Town",
    distanceFromCoimbatoreKm: 68,
    durationFromCoimbatoreHours: 2.0
  },
  "aliyar-dam": {
    id: "p-aliyar-dam",
    canonicalName: "Aliyar Dam & Reservoir",
    name: "Aliyar Dam",
    slug: "aliyar-dam",
    entityType: "POI",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.4836,
    longitude: 76.9722,
    categories: ["dams", "rivers", "tourist-places"],
    primaryCategory: "dams",
    tagline: "Scenic masonry reservoir at the foothills of Valparai with manicured gardens",
    description: "Located at the foot of the Anamalai Hills along the Pollachi-Valparai road, Aliyar Dam is a major reservoir built across the Aliyar River featuring manicured gardens, children's park, and fish aquarium.",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Aliyar-Dam-TopView.jpg",
    verified: true,
    source: "TN Public Works Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["aliyar", "coimbatore", "dams", "pollachi", "reservoir", "gardens"],
    highlights: [
      "Sprawling Reservoir Panoramas",
      "Lush Manicured Public Gardens",
      "State Fish Aquarium",
      "Gateway to Valparai 40 Hairpins"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "September to March",
      duration: "2-3 hours",
      accessPermissions: "Open public access. Nominal entry fee for park.",
      roadCondition: "Excellent 4-lane & state highway."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Pollachi & Anamalai Region",
    taluk: "Anaimalai",
    nearbyTown: "Pollachi (24 km)",
    distanceFromCoimbatoreKm: 64,
    durationFromCoimbatoreHours: 1.5
  },
  "topslip": {
    id: "p-topslip",
    canonicalName: "Topslip (Anamalai Tiger Reserve)",
    name: "Topslip",
    slug: "topslip",
    entityType: "POI",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.4746,
    longitude: 76.8407,
    categories: ["wildlife", "trekking", "tourist-places"],
    primaryCategory: "wildlife",
    tagline: "Elephant sanctuary & forest hub named after colonial timber sliding slopes",
    description: "Situated at 750m in Anamalai Tiger Reserve, Topslip got its name during colonial timber sliding operations. Today it is a renowned sanctuary housing Kozhikamuthi Elephant Camp and guided forest safaris.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Forest Department",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["topslip", "coimbatore", "wildlife", "anamalai", "elephant_camp", "safari"],
    highlights: [
      "Kozhikamuthi Elephant Camp",
      "Forest Department Van Safari",
      "Guided Forest Trekking Trails",
      "Medicinal Plants Garden"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to March",
      duration: "Full day",
      accessPermissions: "Entry checkpoint at Sethumadai. TN Forest Dept safari ticket required.",
      forestPermitRequired: true,
      roadCondition: "Good mountain asphalt till Sethumadai."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Pollachi & Anamalai Region",
    taluk: "Anaimalai",
    nearbyTown: "Pollachi (37 km)",
    distanceFromCoimbatoreKm: 75,
    durationFromCoimbatoreHours: 2.0
  },
  "pollachi": {
    id: "p-pollachi",
    canonicalName: "Pollachi Town & Countryside",
    name: "Pollachi",
    slug: "pollachi",
    entityType: "TOWN",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.6580,
    longitude: 77.0083,
    categories: ["tourist-places", "heritage", "food"],
    primaryCategory: "tourist-places",
    tagline: "Coconut capital of Tamil Nadu & gateway to the Anamalai Western Ghats",
    description: "Situated south of Coimbatore, Pollachi is famed for endless coconut groves, pleasant weather, jaggery and cattle markets, and as a backdrop for South Indian films.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "District Administration",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["pollachi", "coimbatore", "coconuts", "gateway", "countryside"],
    highlights: [
      "Endless Coconut Plantations",
      "Subrahmanya Swamy Temple",
      "South India's Largest Jaggery Market",
      "Eco-Tourism Farm Stays"
    ],
    placeType: "town",
    metadata: {
      bestTime: "Throughout the year",
      duration: "Day trip",
      accessPermissions: "Open public access.",
      roadCondition: "Excellent NH-83 4-lane corridor."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Pollachi & Anamalai Region",
    taluk: "Pollachi",
    nearbyTown: "Pollachi Town",
    distanceFromCoimbatoreKm: 44,
    durationFromCoimbatoreHours: 1.0
  },
  "nelliyampathy": {
    id: "p-nelliyampathy",
    canonicalName: "Nelliyampathy Hill Station",
    name: "Nelliyampathy",
    slug: "nelliyampathy",
    entityType: "HILL",
    district: "Palakkad",
    state: "Kerala",
    country: "India",
    latitude: 10.5356,
    longitude: 76.6936,
    categories: ["hills", "nature", "trekking"],
    primaryCategory: "hills",
    tagline: "Misty tea, coffee & orange plantations atop Palakkad's Western Ghats",
    description: "Known for bio-tea and orange groves, Nelliyampathy is an unspoiled Kerala hill station reached via 23 dramatic hairpin bends from Nenmara with panoramic views across Palakkad Gap.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Kerala Tourism",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["nelliyampathy", "palakkad", "kerala", "hills", "tea_estates", "hairpins"],
    highlights: [
      "Seetharkundu Viewpoint Cliff",
      "Kesavan Para Rock Plateau",
      "Pothundi Dam En Route",
      "Organic Tea & Orange Estates"
    ],
    placeType: "town",
    metadata: {
      bestTime: "September to February",
      duration: "1-2 days",
      accessPermissions: "Open public road access via Pothundi check post.",
      roadCondition: "Good mountain road with 23 hairpin bends."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Palakkad & Neighboring Kerala",
    taluk: "Chittur",
    nearbyTown: "Nenmara (30 km)",
    distanceFromCoimbatoreKm: 110,
    durationFromCoimbatoreHours: 3.0
  },
  "bhavanisagar-dam": {
    id: "p-bhavanisagar-dam",
    canonicalName: "Bhavanisagar Dam & Reservoir",
    name: "Bhavanisagar Dam",
    slug: "bhavanisagar-dam",
    entityType: "POI",
    district: "Erode",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.4705,
    longitude: 77.1165,
    categories: ["dams", "rivers", "tourist-places"],
    primaryCategory: "dams",
    tagline: "World's largest earthen dam at the confluence of Bhavani & Moyar rivers",
    description: "Constructed in 1953, Bhavanisagar is a massive 8 km earthen dam in Sathyamangalam taluk, Erode district, harnessing waters where the Bhavani and Moyar rivers meet.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/BhavaniSagarDam.JPG/1280px-BhavaniSagarDam.JPG",
    verified: true,
    source: "TN Water Resources Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["bhavanisagar", "erode", "dams", "sathyamangalam", "bhavani_river", "reservoir"],
    highlights: [
      "8 km World-Class Earthen Dam Structure",
      "Bhavani & Moyar Confluence Point",
      "Children's Riverside Park & Boating",
      "Fresh Freshwater Fish Delicacies"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to March",
      duration: "3-4 hours",
      accessPermissions: "Open public access to park. Dam top access restricted.",
      roadCondition: "Good state highway from Mettupalayam / Sathy."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Erode & Sathyamangalam Region",
    taluk: "Sathyamangalam",
    nearbyTown: "Sathyamangalam (16 km)",
    distanceFromCoimbatoreKm: 80,
    durationFromCoimbatoreHours: 2.0
  },
  "valparai": {
    id: "p-valparai-hill-station",
    canonicalName: "Valparai Hill Station",
    name: "Valparai",
    slug: "valparai",
    entityType: "HILL",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.3270,
    longitude: 76.9554,
    categories: ["hills", "wildlife", "waterfalls"],
    primaryCategory: "hills",
    tagline: "High-altitude tea plateau surrounded by Nilgiri Tahr & Lion-tailed Macaques",
    description: "Standing at 1,075m in the Anamalai Hills, Valparai is reached via 40 hairpin bends from Aliyar. Surrounded by tea estates, Sholayar Dam, and Chinnakallar, it offers pristine wildlife habitats.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Tourism",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["valparai", "coimbatore", "hills", "tea_estates", "hairpin_bends", "wildlife"],
    highlights: [
      "40 Hairpin Bend Ghat Pass",
      "Chinnakallar Waterfalls & Suspension Bridge",
      "Sholayar Dam Reservoir",
      "Lion-tailed Macaque & Nilgiri Tahr Habitat"
    ],
    placeType: "town",
    metadata: {
      bestTime: "September to March",
      duration: "2 days",
      accessPermissions: "Open public access. Checkpoints active for plastic enforcement.",
      roadCondition: "Scenic 40 hairpin bend ghat road; drive carefully."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Pollachi & Anamalai Region",
    taluk: "Valparai",
    nearbyTown: "Pollachi (64 km)",
    distanceFromCoimbatoreKm: 104,
    durationFromCoimbatoreHours: 3.5
  },
  "siruvani-waterfalls": {
    id: "p-siruvani-waterfalls",
    canonicalName: "Siruvani Waterfalls & Dam",
    name: "Siruvani Waterfalls",
    slug: "siruvani-waterfalls",
    entityType: "WATERFALL",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.9387,
    longitude: 76.6876,
    categories: ["waterfalls", "wildlife", "nature"],
    primaryCategory: "waterfalls",
    tagline: "Source of the world's second sweetest drinking water amidst reserve forest",
    description: "Tucked inside Western Ghats reserve forest west of Coimbatore, Siruvani Waterfalls feeds the famous Siruvani Reservoir, world-renowned for its sweet tasting mineral water.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["siruvani", "coimbatore", "waterfalls", "sweet_water", "sadivayal", "forest_safari"],
    highlights: [
      "World-Renowned Sweet Mineral Water Source",
      "Forest Dept Eco-Safari Van Ride",
      "Deep Western Ghats Canopy Trek",
      "Sadivayal Gateway & River Crossing"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "September to January",
      duration: "Half day",
      accessPermissions: "Strict entry via TN Forest Dept bus at Sadivayal check post.",
      forestPermitRequired: true,
      roadCondition: "Good road to Sadivayal check post."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Coimbatore Outskirts & Western Surroundings",
    taluk: "Perur",
    nearbyTown: "Coimbatore City (36 km)",
    distanceFromCoimbatoreKm: 36,
    durationFromCoimbatoreHours: 1.0
  },
  "kotagiri": {
    id: "p-kotagiri-hills",
    canonicalName: "Kotagiri Hill Station",
    name: "Kotagiri",
    slug: "kotagiri",
    entityType: "HILL",
    district: "The Nilgiris",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.4248,
    longitude: 76.8587,
    categories: ["hills", "waterfalls", "trekking"],
    primaryCategory: "hills",
    tagline: "Oldest Nilgiri hill station surrounded by Catherine Falls & Kota history",
    description: "Perched at 1,793m, Kotagiri is the oldest Nilgiri hill station with an equitable climate year-round. Home to Catherine Falls, Kodanad Viewpoint, and Longwood Shola forest.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Tourism",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["kotagiri", "nilgiris", "hills", "catherine_falls", "kodanad", "shola_forest"],
    highlights: [
      "Kodanad Viewpoint (Moyar River Valley)",
      "Double-tiered Catherine Falls",
      "Longwood Shola Virgin Forest Trek",
      "John Sullivan Building Museum"
    ],
    placeType: "town",
    metadata: {
      bestTime: "September to May",
      duration: "1-2 days",
      accessPermissions: "Open public access.",
      roadCondition: "Good tarmac ghat road via Mettupalayam."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Nilgiris",
    taluk: "Kotagiri",
    nearbyTown: "Mettupalayam (33 km)",
    distanceFromCoimbatoreKm: 66,
    durationFromCoimbatoreHours: 2.0
  },
  "velliangiri-hills": {
    id: "p-velliangiri-hills",
    canonicalName: "Velliangiri Hills & Poondi Temple (South Kailash)",
    name: "Velliangiri Hills",
    slug: "velliangiri-hills",
    entityType: "POI",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.9859,
    longitude: 76.6896,
    categories: ["temples", "trekking", "hills"],
    primaryCategory: "temples",
    tagline: "The legendary 'South Kailash' — 7-hill sacred pilgrimage trek through reserve forest",
    description: "Rising to 1,778m west of Coimbatore, Velliangiri Hills are revered as 'South Kailash'. The strenuous 7-hill trek passes through dense shola forests ending at a natural cave Shiva shrine.",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/83/Velliangiri_Mountains.jpg",
    verified: true,
    source: "HR&CE & Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["velliangiri", "coimbatore", "south_kailash", "poondi", "temple", "trekking"],
    highlights: [
      "7-Hill Sacred Wilderness Trek",
      "Poondi Velliangiri Andavar Temple",
      "Natural Cave Shiva Lingam at 7th Hill",
      "Proximity to Isha Yoga Center"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "February to May (Mahashivratri Season)",
      duration: "1 night trek",
      accessPermissions: "Trek permitted Feb-May. Registration & bamboo stick check at Poondi base.",
      forestPermitRequired: true,
      roadCondition: "Paved road to Poondi temple base."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Coimbatore Outskirts & Western Surroundings",
    taluk: "Perur",
    nearbyTown: "Coimbatore City (30 km)",
    distanceFromCoimbatoreKm: 30,
    durationFromCoimbatoreHours: 0.75
  },
  "anaikatti": {
    id: "p-anaikatti-valley",
    canonicalName: "Anaikatti Valley & Siruvani River Stretch",
    name: "Anaikatti",
    slug: "anaikatti",
    entityType: "TOWN",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.1042,
    longitude: 76.7725,
    categories: ["nature", "wildlife", "tourist-places"],
    primaryCategory: "nature",
    tagline: "Serene river valley & elephant corridor on the Tamil Nadu-Kerala border",
    description: "Translating to 'Group of Elephants', Anaikatti is a picturesque hill valley on the border of Tamil Nadu and Kerala along the Siruvani River, famed for eco-resorts and elephant corridors.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "District Administration",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["anaikatti", "coimbatore", "siruvani_river", "elephant_corridor", "valley"],
    highlights: [
      "Siruvani River Bank Eco-Stays",
      "SACON Bird & Nature Trails",
      "Western Ghats Forest Gap Landscape",
      "Kerala Border Bridge Crossing"
    ],
    placeType: "town",
    metadata: {
      bestTime: "September to March",
      duration: "Day trip / 1 night",
      accessPermissions: "Open public road access via Thadagam gap.",
      roadCondition: "Good state road via Thadagam valley."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Coimbatore Outskirts & Western Surroundings",
    taluk: "Coimbatore North",
    nearbyTown: "Coimbatore City (30 km)",
    distanceFromCoimbatoreKm: 30,
    durationFromCoimbatoreHours: 0.75
  },
  "palamalai": {
    id: "p-palamalai-temple",
    canonicalName: "Palamalai Perumal Temple & Hills",
    name: "Palamalai",
    slug: "palamalai",
    entityType: "POI",
    district: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.1711,
    longitude: 76.9082,
    categories: ["temples", "hills", "trekking"],
    primaryCategory: "temples",
    tagline: "Hilltop Ranganathar temple nestled in dense reserve forest near Periyanaickenpalayam",
    description: "Palamalai is a tranquil hill peak near Periyanaickenpalayam north of Coimbatore, home to Sri Palamalai Ranganathar Temple reached via a 6 km winding hill drive or trekking steps.",
    image: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "HR&CE Department",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["palamalai", "coimbatore", "temple", "ranganathar", "periyanaickenpalayam", "hills"],
    highlights: [
      "Historic Sri Palamalai Ranganathar Shrine",
      "Panoramic Views over Mettupalayam Plains",
      "6 km Scenic Hill Drive & Step Trek",
      "Peaceful Reserve Forest Environment"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "Throughout the year",
      duration: "Half day",
      accessPermissions: "Open public access. Hill road maintained by temple trust.",
      roadCondition: "Narrow asphalt hill road with winding bends."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Coimbatore Outskirts & Western Surroundings",
    taluk: "Periyanaickenpalayam",
    nearbyTown: "Periyanaickenpalayam (6 km)",
    distanceFromCoimbatoreKm: 25,
    durationFromCoimbatoreHours: 0.6
  },
  "dhimbam": {
    id: "p-dhimbam-ghats",
    canonicalName: "Dhimbam Ghats & Viewpoint (Sathyamangalam)",
    name: "Dhimbam",
    slug: "dhimbam",
    entityType: "POI",
    district: "Erode",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.6053,
    longitude: 77.1642,
    categories: ["hills", "wildlife", "nature"],
    primaryCategory: "hills",
    tagline: "Thrilling 27-hairpin bend mountain pass through Sathyamangalam Tiger Reserve",
    description: "Dhimbam (Dhimbum) is a famous mountain pass along NH-948 connecting Tamil Nadu to Karnataka through Sathyamangalam Tiger Reserve. Ascending through 27 hairpin bends from Bannari temple.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Highways & Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["dhimbam", "dhimbum", "erode", "sathyamangalam", "hairpin_bends", "bannari", "tiger_reserve"],
    highlights: [
      "27 Hairpin Bend Engineering Marvel",
      "Bannari Amman Foothill Temple",
      "Sathyamangalam Tiger Reserve Views",
      "Hasanur Plateau Forest Drive"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "September to March",
      duration: "Day trip",
      accessPermissions: "National Highway. Night travel restrictions enforced for heavy vehicles.",
      roadCondition: "Steep 27 hairpin National Highway ghat pass."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Erode & Sathyamangalam Region",
    taluk: "Sathyamangalam",
    nearbyTown: "Sathyamangalam (28 km)",
    distanceFromCoimbatoreKm: 95,
    durationFromCoimbatoreHours: 2.5
  },
  "munnar": {
    id: "p-munnar-hill-station",
    canonicalName: "Munnar Hill Station",
    name: "Munnar",
    slug: "munnar",
    entityType: "HILL",
    district: "Idukki",
    state: "Kerala",
    country: "India",
    latitude: 10.0889,
    longitude: 77.0595,
    categories: ["hills", "nature", "wildlife", "tourist-places"],
    primaryCategory: "hills",
    tagline: "World-famous tea garden paradise at the confluence of three mountain streams",
    description: "Situated at 1,600m in Kerala's Idukki district, Munnar is connected to Coimbatore via the Udumalpet-Chinnar route, famed for rolling tea plantations, Eravikulam National Park, and Mattupetty Dam.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Kerala Tourism",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["munnar", "idukki", "kerala", "hills", "tea_estates", "eravikulam"],
    highlights: [
      "Eravikulam National Park (Nilgiri Tahr)",
      "Vast Rolling Tea Plantations & Museum",
      "Mattupetty Dam & Speedboating",
      "Chinnar Wildlife Sanctuary En Route"
    ],
    placeType: "town",
    metadata: {
      bestTime: "September to May",
      duration: "2-3 days",
      accessPermissions: "Eravikulam requires online tickets. Inter-state border check at Chinnar.",
      roadCondition: "Scenic mountain corridor via Udumalpet & Marayoor."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Munnar & Western Ghats",
    taluk: "Devikulam",
    nearbyTown: "Udumalpet (85 km)",
    distanceFromCoimbatoreKm: 155,
    durationFromCoimbatoreHours: 4.5
  },
  "rakachi-amman-falls": {
    id: "p-rakachi-amman-falls",
    canonicalName: "Sri Rakachi Amman Kovil & Waterfalls",
    name: "Sri Rakachi Amman Kovil Falls",
    slug: "rakachi-amman-falls",
    entityType: "WATERFALL",
    district: "Virudhunagar",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.4184,
    longitude: 77.4691,
    categories: ["waterfalls", "temples", "trekking", "nature"],
    primaryCategory: "waterfalls",
    tagline: "Forest cascade & sacred shrine in the Western Ghats foothills near Rajapalayam",
    description: "Nestled in the foothills of Srivilliputhur-Megamalai Tiger Reserve near Rajapalayam, Sri Rakachi Amman Kovil Falls features crystal-clear herbal streams originating from unpolluted mountain peaks.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Virudhunagar District Administration",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:30:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["rakachi_amman", "ayyanar_kovil", "rajapalayam", "virudhunagar", "waterfalls", "herbal_stream"],
    highlights: [
      "Sacred Herbal Forest Cascade",
      "Sri Rakachi Amman & Ayyanar Shrines",
      "Srivilliputhur-Megamalai Western Ghats Foothills",
      "Ayyanar Kovil Dam & Trekking Trails"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to February",
      duration: "Weekend trip",
      accessPermissions: "Forest entry regulated at Mudangiar check post. Bathing restricted during floods.",
      roadCondition: "Good tarmac to Mudangiar check post; short forest path."
    },
    travelOrigins: ["coimbatore"],
    geographicRegion: "Rajapalayam & Southern Tamil Nadu",
    taluk: "Rajapalayam",
    nearbyTown: "Rajapalayam (8 km)",
    distanceFromCoimbatoreKm: 245,
    durationFromCoimbatoreHours: 5.5
  }
};
