export interface DistrictAdminDetails {
  code: string;
  headquarters: string;
  established: string;
  predecessor: string;
  areaKm2: number;
  population: number;
  popDensityPerKm2: number;
  revenueDivisions: string[];
  taluks: string[];
  assemblyConstituencies: string[];
  lokSabhaConstituencies: string[];
}

export const TAMIL_NADU_DISTRICT_ADMIN_DATA: Record<string, DistrictAdminDetails> = {
  ariyalur: {
    code: "ARI",
    headquarters: "Ariyalur",
    established: "23 November 2007",
    predecessor: "Perambalur",
    areaKm2: 2027.6,
    population: 754894,
    popDensityPerKm2: 372,
    revenueDivisions: ["Ariyalur", "Udayarpalayam"],
    taluks: ["Andimadam", "Ariyalur", "Sendurai", "Udayarpalayam"],
    assemblyConstituencies: ["Ariyalur", "Jayankondam"],
    lokSabhaConstituencies: ["Chidambaram"],
  },
  chengalpattu: {
    code: "CHG",
    headquarters: "Chengalpattu",
    established: "29 November 2019",
    predecessor: "Kanchipuram",
    areaKm2: 2802.6,
    population: 2556244,
    popDensityPerKm2: 912,
    revenueDivisions: ["Chengalpattu", "Madurantakam", "Tambaram"],
    taluks: ["Chengalpattu", "Cheyyur", "Madurantakam", "Pallavaram", "Tambaram", "Thiruporur", "Thirukazhukundram", "Vandalur"],
    assemblyConstituencies: ["Cheyyur", "Chengalpattu", "Maduranthakam", "Pallavaram", "Tambaram", "Thiruporur"],
    lokSabhaConstituencies: ["Kancheepuram", "Sriperumbudur"],
  },
  chennai: {
    code: "CHN",
    headquarters: "Chennai",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 462.3,
    population: 6748026,
    popDensityPerKm2: 10052,
    revenueDivisions: ["Chennai Central", "Chennai North", "Chennai South"],
    taluks: ["Alandur", "Ambattur", "Aminjikarai", "Ayanavaram", "Egmore", "Guindy", "Kolathur", "Madhavaram", "Maduravoyal", "Mambalam", "Thirumayilai", "Perambur", "Purasawalkam", "Sholinganallur", "Tiruvottiyur", "Tondiarpet", "Velachery"],
    assemblyConstituencies: ["Alandur", "Ambattur", "Anna Nagar", "Chepauk-Thiruvallikeni", "Dr. Radhakrishnan Nagar", "Egmore", "Harbour", "Kolathur", "Maduravoyal", "Madhavaram", "Perambur", "Royapuram", "Saidapet", "Sholinganallur", "Thiru-Vi-Ka Nagar", "Thirumayilai", "Thiruvottiyur", "Thousand Lights", "Thyagaraya Nagar", "Velachery", "Villivakkam", "Virugambakkam"],
    lokSabhaConstituencies: ["Chennai Central", "Chennai North", "Chennai South", "Sriperumbudur", "Thiruvallur"],
  },
  coimbatore: {
    code: "COI",
    headquarters: "Coimbatore",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 4950.7,
    population: 3458045,
    popDensityPerKm2: 699,
    revenueDivisions: ["Coimbatore North", "Coimbatore South", "Pollachi"],
    taluks: ["Anaimalai", "Annur", "Coimbatore North", "Coimbatore South", "Kinathukadavu", "Madukkarai", "Mettupalayam", "Perur", "Pollachi", "Sulur", "Valparai"],
    assemblyConstituencies: ["Kavundampalayam", "Kinathukadavu", "Mettupalayam", "Pollachi", "Coimbatore North", "Coimbatore South", "Singanallur", "Sulur", "Thondamuthur", "Valparai"],
    lokSabhaConstituencies: ["Coimbatore", "Nilgiris", "Pollachi"],
  },
  cuddalore: {
    code: "CUD",
    headquarters: "Cuddalore",
    established: "30 September 1993",
    predecessor: "South Arcot District",
    areaKm2: 3870,
    population: 2605914,
    popDensityPerKm2: 673,
    revenueDivisions: ["Chidambaram", "Cuddalore", "Vriddhachalam"],
    taluks: ["Bhuvanagiri", "Chidambaram", "Cuddalore", "Kattumannarkoil", "Kurinjipadi", "Panruti", "Srimushnam", "Titakudi", "Veppur", "Vriddhachalam"],
    assemblyConstituencies: ["Bhuvanagiri", "Chidambaram", "Cuddalore", "Kattumannarkoil", "Kurinjipadi", "Neyveli", "Panruti", "Tittakudi", "Virudhachalam"],
    lokSabhaConstituencies: ["Chidambaram", "Cuddalore"],
  },
  dharmapuri: {
    code: "DHA",
    headquarters: "Dharmapuri",
    established: "2 October 1965",
    predecessor: "Salem",
    areaKm2: 4735.7,
    population: 1506843,
    popDensityPerKm2: 318,
    revenueDivisions: ["Dharmapuri", "Harur"],
    taluks: ["Dharmapuri", "Harur", "Karimangalam", "Nallampalli", "Palacode", "Pappireddipatti", "Pennagaram"],
    assemblyConstituencies: ["Dharmapuri", "Harur", "Palacode", "Pappireddipatti", "Pennagaram"],
    lokSabhaConstituencies: ["Dharmapuri"],
  },
  dindigul: {
    code: "DIN",
    headquarters: "Dindigul",
    established: "15 September 1985",
    predecessor: "Madurai",
    areaKm2: 6289.1,
    population: 2159775,
    popDensityPerKm2: 343,
    revenueDivisions: ["Dindigul", "Kodaikanal", "Palani"],
    taluks: ["Athoor", "Dindigul-East", "Dindigul-West", "Gujiliamparai", "Kodaikanal", "Natham", "Nilakottai", "Oddanchattiram", "Palani", "Vedasandur"],
    assemblyConstituencies: ["Athoor", "Dindigul", "Natham", "Nilakottai", "Oddanchatram", "Palani", "Vedasandur"],
    lokSabhaConstituencies: ["Dindigul", "Karur"],
  },
  erode: {
    code: "ERO",
    headquarters: "Erode",
    established: "31 August 1979",
    predecessor: "Coimbatore",
    areaKm2: 6036,
    population: 2251744,
    popDensityPerKm2: 373,
    revenueDivisions: ["Erode", "Gobichettipalayam"],
    taluks: ["Anthiyur", "Bhavani", "Erode", "Gobichettipalayam", "Kodumudi", "Modakurichi", "Nambiyur", "Perundurai", "Sathyamangalam", "Thalavadi"],
    assemblyConstituencies: ["Anthiyur", "Bhavani", "Bhavanisagar", "Erode East", "Erode West", "Gobichettipalayam", "Modakkurichi", "Perundurai"],
    lokSabhaConstituencies: ["Erode", "Nilgiris", "Tiruppur"],
  },
  kallakurichi: {
    code: "KAL",
    headquarters: "Kallakurichi",
    established: "26 November 2019",
    predecessor: "Viluppuram",
    areaKm2: 3440.8,
    population: 1370281,
    popDensityPerKm2: 398,
    revenueDivisions: ["Kallakurichi", "Thirukoilur"],
    taluks: ["Chinnasalem", "Kallakurichi", "Kalvarayan Malai", "Sankarapuram", "Thirukoilur", "Ulundurpet", "Vanapuram"],
    assemblyConstituencies: ["Kallakurichi", "Rishivandiyam", "Sankarapuram", "Tirukkoyilur", "Ulundurpettai"],
    lokSabhaConstituencies: ["Kallakurichi", "Viluppuram"],
  },
  kancheepuram: {
    code: "KAC",
    headquarters: "Kancheepuram",
    established: "1 July 1997",
    predecessor: "Chingleput",
    areaKm2: 1800.2,
    population: 1166401,
    popDensityPerKm2: 648,
    revenueDivisions: ["Kancheepuram", "Sriperumbudur"],
    taluks: ["Kancheepuram", "Kundrathur", "Sriperumbudur", "Uthiramerur", "Walajabad"],
    assemblyConstituencies: ["Kancheepuram", "Sriperumbudur", "Uthiramerur"],
    lokSabhaConstituencies: ["Kancheepuram", "Sriperumbudur"],
  },
  kanniyakumari: {
    code: "KAY",
    headquarters: "Nagercoil",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 1729.2,
    population: 1870374,
    popDensityPerKm2: 1082,
    revenueDivisions: ["Nagercoil", "Padmanabhapuram"],
    taluks: ["Agastheeswaram", "Kalkulam", "Killiyoor", "Vilavancode", "Thiruvattar", "Thovalai"],
    assemblyConstituencies: ["Colachal", "Kanniyakumari", "Killiyur", "Nagercoil", "Padmanabhapuram", "Vilavancode"],
    lokSabhaConstituencies: ["Kanniyakumari"],
  },
  kanyakumari: {
    code: "KAY",
    headquarters: "Nagercoil",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 1729.2,
    population: 1870374,
    popDensityPerKm2: 1082,
    revenueDivisions: ["Nagercoil", "Padmanabhapuram"],
    taluks: ["Agastheeswaram", "Kalkulam", "Killiyoor", "Vilavancode", "Thiruvattar", "Thovalai"],
    assemblyConstituencies: ["Colachal", "Kanniyakumari", "Killiyur", "Nagercoil", "Padmanabhapuram", "Vilavancode"],
    lokSabhaConstituencies: ["Kanniyakumari"],
  },
  karur: {
    code: "KAR",
    headquarters: "Karur",
    established: "30 September 1995",
    predecessor: "Tiruchirappalli",
    areaKm2: 3022.3,
    population: 1064493,
    popDensityPerKm2: 352,
    revenueDivisions: ["Karur", "Kulithalai"],
    taluks: ["Aravakurichi", "Kadavur", "Karur", "Krishnarayapuram", "Kulithalai", "Manmangalam", "Pugalur"],
    assemblyConstituencies: ["Aravakurichi", "Karur", "Krishnarayapuram", "Kulithalai"],
    lokSabhaConstituencies: ["Karur", "Perambalur"],
  },
  krishnagiri: {
    code: "KRI",
    headquarters: "Krishnagiri",
    established: "9 February 2004",
    predecessor: "Dharmapuri",
    areaKm2: 5414.4,
    population: 1883731,
    popDensityPerKm2: 348,
    revenueDivisions: ["Hosur", "Krishnagiri"],
    taluks: ["Anchetty", "Bargur", "Denkanikottai", "Hosur", "Krishnagiri", "Pochampalli", "Shoolagiri", "Uthangarai"],
    assemblyConstituencies: ["Bargur", "Hosur", "Krishnagiri", "Thalli", "Uthangarai", "Veppanapalli"],
    lokSabhaConstituencies: ["Krishnagiri"],
  },
  madurai: {
    code: "MAD",
    headquarters: "Madurai",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 3846.4,
    population: 3038252,
    popDensityPerKm2: 790,
    revenueDivisions: ["Madurai", "Melur", "Usilampatti"],
    taluks: ["Madurai-East", "Madurai-North", "Madurai-South", "Madurai-West", "Kallikudi", "Melur", "Peraiyur", "Thirumangalam", "Thirupparankundram", "Usilampatti", "Vadipatti"],
    assemblyConstituencies: ["Madurai Central", "Madurai East", "Madurai North", "Madurai South", "Madurai West", "Melur", "Sholavandan", "Thirumangalam", "Thiruparankundram", "Usilampatti"],
    lokSabhaConstituencies: ["Madurai", "Theni", "Virudhunagar"],
  },
  mayiladuthurai: {
    code: "MAY",
    headquarters: "Mayiladuthurai",
    established: "28 December 2020",
    predecessor: "Nagapattinam",
    areaKm2: 1237.1,
    population: 918356,
    popDensityPerKm2: 742,
    revenueDivisions: ["Mayiladuthurai", "Sirkazhi"],
    taluks: ["Kuthalam", "Mayiladuthurai", "Sirkazhi", "Tharangambadi"],
    assemblyConstituencies: ["Mayiladuthurai", "Poompuhar", "Sirkazhi"],
    lokSabhaConstituencies: ["Mayiladuthurai"],
  },
  nagapattinam: {
    code: "NAG",
    headquarters: "Nagapattinam",
    established: "18 October 1991",
    predecessor: "Thanjavur",
    areaKm2: 1459,
    population: 697069,
    popDensityPerKm2: 478,
    revenueDivisions: ["Nagapattinam", "Vedaranyam"],
    taluks: ["Kilvelur", "Nagapattinam", "Thirukkuvalai", "Vedaranyam"],
    assemblyConstituencies: ["Kilvelur", "Nagapattinam", "Vedaranyam"],
    lokSabhaConstituencies: ["Nagapattinam"],
  },
  namakkal: {
    code: "NAM",
    headquarters: "Namakkal",
    established: "1 January 1997",
    predecessor: "Salem",
    areaKm2: 3573.4,
    population: 1726601,
    popDensityPerKm2: 483,
    revenueDivisions: ["Namakkal", "Tiruchengode"],
    taluks: ["Kolli Hills", "Kumarapalayam", "Mohanur", "Namakkal", "Paramathi-Velur", "Rasipuram", "Senthamangalam", "Tiruchengode"],
    assemblyConstituencies: ["Namakkal", "Kumarapalayam", "Paramathi-Velur", "Rasipuram", "Senthamangalam", "Thiruchengode"],
    lokSabhaConstituencies: ["Erode", "Namakkal"],
  },
  "the-nilgiris": {
    code: "NIL",
    headquarters: "Ooty",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 2452.5,
    population: 735394,
    popDensityPerKm2: 300,
    revenueDivisions: ["Coonoor", "Gudalur", "Udagamandalam"],
    taluks: ["Coonoor", "Gudalur", "Kotagiri", "Kundah", "Pandalur", "Udagamandalam"],
    assemblyConstituencies: ["Coonoor", "Gudalur", "Udagamandalam"],
    lokSabhaConstituencies: ["Nilgiris"],
  },
  nilgiris: {
    code: "NIL",
    headquarters: "Ooty",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 2452.5,
    population: 735394,
    popDensityPerKm2: 300,
    revenueDivisions: ["Coonoor", "Gudalur", "Udagamandalam"],
    taluks: ["Coonoor", "Gudalur", "Kotagiri", "Kundah", "Pandalur", "Udagamandalam"],
    assemblyConstituencies: ["Coonoor", "Gudalur", "Udagamandalam"],
    lokSabhaConstituencies: ["Nilgiris"],
  },
  perambalur: {
    code: "PER",
    headquarters: "Perambalur",
    established: "30 September 1995",
    predecessor: "Tiruchirappalli",
    areaKm2: 1836.6,
    population: 565223,
    popDensityPerKm2: 308,
    revenueDivisions: ["Perambalur"],
    taluks: ["Alathur", "Kunnam", "Perambalur", "Veppanthattai"],
    assemblyConstituencies: ["Kunnam", "Perambalur"],
    lokSabhaConstituencies: ["Perambalur"],
  },
  pudukkottai: {
    code: "PUD",
    headquarters: "Pudukkottai",
    established: "14 January 1974",
    predecessor: "Thanjavur and Tiruchirappalli",
    areaKm2: 4847.8,
    population: 1618345,
    popDensityPerKm2: 334,
    revenueDivisions: ["Aranthangi", "Illuppur", "Pudukkottai"],
    taluks: ["Alangudi", "Aranthangi", "Avadaiyarkoil", "Gandarvakottai", "Illuppur", "Karambakkudi", "Kulathur", "Manamelkudi", "Ponnamaravathi", "Pudukkottai", "Thirumayam", "Viralimalai"],
    assemblyConstituencies: ["Alangudi", "Aranthangi", "Gandarvakottai", "Pudukkottai", "Thirumayam", "Viralimalai"],
    lokSabhaConstituencies: ["Karur", "Ramanathapuram", "Sivaganga", "Tiruchirappalli"],
  },
  ramanathapuram: {
    code: "RAM",
    headquarters: "Ramanathapuram",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 4243.1,
    population: 1353445,
    popDensityPerKm2: 319,
    revenueDivisions: ["Paramakudi", "Ramanathapuram"],
    taluks: ["Kadaladi", "Kamuthi", "Kilakarai", "Mudukulathur", "Paramakudi", "Rajasingamangalam", "Ramanathapuram", "Rameswaram", "Tiruvadanai"],
    assemblyConstituencies: ["Mudukulathur", "Paramakudi", "Ramanathapuram", "Tiruvadanai"],
    lokSabhaConstituencies: ["Ramanathapuram"],
  },
  ranipet: {
    code: "RAN",
    headquarters: "Ranipet",
    established: "28 November 2019",
    predecessor: "Vellore",
    areaKm2: 2234.3,
    population: 1210277,
    popDensityPerKm2: 542,
    revenueDivisions: ["Arakkonam", "Ranipet"],
    taluks: ["Arakkonam", "Arkadu", "Kalavai", "Nemili", "Sholinghur", "Walajapet"],
    assemblyConstituencies: ["Arakkonam", "Arcot", "Ranipet", "Sholingur"],
    lokSabhaConstituencies: ["Arakkonam"],
  },
  salem: {
    code: "SAL",
    headquarters: "Salem",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 5245,
    population: 3482056,
    popDensityPerKm2: 669,
    revenueDivisions: ["Attur", "Mettur", "Salem", "Sankagiri"],
    taluks: ["Attur", "Idappadi", "Gangavalli", "Kadayampatti", "Mettur", "Omalur", "Pethanaickenpalayam", "Salem", "Salem South", "Salem West", "Sankagiri", "Thalaivasal", "Vazhapady", "Yercaud"],
    assemblyConstituencies: ["Attur", "Edappadi", "Gangavalli", "Mettur", "Omalur", "Sankari", "Salem North", "Salem South", "Salem West", "Veerapandi", "Yercaud"],
    lokSabhaConstituencies: ["Dharmapuri", "Kallakurichi", "Namakkal", "Salem"],
  },
  sivaganga: {
    code: "SIV",
    headquarters: "Sivaganga",
    established: "15 March 1985",
    predecessor: "Ramanathapuram",
    areaKm2: 4086,
    population: 1339101,
    popDensityPerKm2: 328,
    revenueDivisions: ["Devakottai", "Sivaganga"],
    taluks: ["Devakottai", "Ilayangudi", "Kalayarkoil", "Karaikudi", "Manamadurai", "Singampunari", "Sivaganga", "Tirupathur", "Tiruppuvanam"],
    assemblyConstituencies: ["Karaikudi", "Manamadurai", "Sivaganga", "Tirupattur"],
    lokSabhaConstituencies: ["Sivaganga"],
  },
  tenkasi: {
    code: "TEN",
    headquarters: "Tenkasi",
    established: "22 November 2019",
    predecessor: "Tirunelveli",
    areaKm2: 2916.1,
    population: 1407627,
    popDensityPerKm2: 483,
    revenueDivisions: ["Sankarankoil", "Tenkasi"],
    taluks: ["Alangulam", "Kadayanallur", "Sankarankoil", "Shenkottai", "Sivagiri", "Tenkasi", "Thiruvengadam", "Veerakeralamputhur"],
    assemblyConstituencies: ["Alangulam", "Kadayanallur", "Sankarankovil", "Tenkasi", "Vasudevanallur"],
    lokSabhaConstituencies: ["Tenkasi", "Tirunelveli"],
  },
  thanjavur: {
    code: "THA",
    headquarters: "Thanjavur",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 3396.6,
    population: 2405890,
    popDensityPerKm2: 708,
    revenueDivisions: ["Kumbakonam", "Pattukkottai", "Thanjavur"],
    taluks: ["Budalur", "Kumbakonam", "Orathanadu", "Papanasam", "Pattukkottai", "Peravurani", "Thanjavur", "Thiruvaiyaru", "Thiruvidaimarudur", "Thiruvonam"],
    assemblyConstituencies: ["Kumbakonam", "Orathanadu", "Papanasam", "Pattukkottai", "Peravurani", "Thanjavur", "Thiruvaiyaru", "Thiruvidaimarudur"],
    lokSabhaConstituencies: ["Mayiladuthurai", "Thanjavur"],
  },
  theni: {
    code: "THE",
    headquarters: "Theni",
    established: "25 July 1996",
    predecessor: "Madurai",
    areaKm2: 3066,
    population: 1245899,
    popDensityPerKm2: 406,
    revenueDivisions: ["Periyakulam", "Uthamapalayam"],
    taluks: ["Andipatti", "Bodinayakanur", "Theni", "Periyakulam", "Uthamapalayam"],
    assemblyConstituencies: ["Andipatti", "Bodinayakanur", "Cumbum", "Periyakulam"],
    lokSabhaConstituencies: ["Theni"],
  },
  thoothukudi: {
    code: "THO",
    headquarters: "Thoothukudi",
    established: "20 October 1986",
    predecessor: "Tirunelveli",
    areaKm2: 4621,
    population: 1750176,
    popDensityPerKm2: 379,
    revenueDivisions: ["Kovilpatti", "Tiruchendur", "Thoothukudi"],
    taluks: ["Eral", "Ettayapuram", "Kayathar", "Kovilpatti", "Ottapidaram", "Sathankulam", "Thiruvaikundam", "Tiruchendur", "Thoothukudi", "Vilathikulam"],
    assemblyConstituencies: ["Vilathikulam", "Thoothukudi", "Tiruchendur", "Srivaikuntam", "Ottapidaram", "Kovilpatti"],
    lokSabhaConstituencies: ["Thoothukudi"],
  },
  tiruchirappalli: {
    code: "TIC",
    headquarters: "Tiruchirappalli",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 4407,
    population: 2722290,
    popDensityPerKm2: 618,
    revenueDivisions: ["Lalgudi", "Manachanallur", "Manapparai", "Musiri", "Srirangam", "Tiruchirappalli"],
    taluks: ["Lalgudi", "Manachanallur", "Manapparai", "Marungapuri", "Musiri", "Srirangam", "Tiruchirappalli West", "Tiruchirappalli East", "Thiruverumbur", "Thottiyam", "Thuraiyur"],
    assemblyConstituencies: ["Lalgudi", "Manachanallur", "Manapparai", "Musiri", "Srirangam", "Thiruverumbur", "Thuraiyur", "Tiruchirappalli East", "Tiruchirappalli West"],
    lokSabhaConstituencies: ["Karur", "Perambalur", "Tiruchirappalli"],
  },
  tirunelveli: {
    code: "TIN",
    headquarters: "Tirunelveli",
    established: "1 November 1956",
    predecessor: "None",
    areaKm2: 3842.4,
    population: 1665253,
    popDensityPerKm2: 433,
    revenueDivisions: ["Cheranmahadevi", "Tirunelveli"],
    taluks: ["Ambasamudram", "Cheranmahadevi", "Manur", "Nanguneri", "Palayamkottai", "Radhapuram", "Tisayanvilai", "Tirunelveli"],
    assemblyConstituencies: ["Ambasamudram", "Nanguneri", "Palayamkottai", "Radhapuram", "Tirunelveli"],
    lokSabhaConstituencies: ["Tirunelveli"],
  },
  tirupathur: {
    code: "TIA",
    headquarters: "Tirupattur",
    established: "28 November 2019",
    predecessor: "Vellore",
    areaKm2: 1792.9,
    population: 1111812,
    popDensityPerKm2: 620,
    revenueDivisions: ["Tirupathur", "Vaniyambadi"],
    taluks: ["Ambur", "Natrampalli", "Tirupathur", "Vaniyambadi"],
    assemblyConstituencies: ["Ambur", "Jolarpet", "Tirupathur", "Vaniyambadi"],
    lokSabhaConstituencies: ["Tiruvannamalai", "Vellore"],
  },
  tiruppur: {
    code: "TIP",
    headquarters: "Tiruppur",
    established: "22 February 2009",
    predecessor: "Coimbatore and Erode",
    areaKm2: 5186.3,
    population: 2479052,
    popDensityPerKm2: 478,
    revenueDivisions: ["Dharapuram", "Tiruppur", "Udumalaipettai"],
    taluks: ["Avinashi", "Dharapuram", "Kangeyam", "Madathukulam", "Palladam", "Tiruppur North", "Tiruppur South", "Udumalaipettai", "Uthukuli"],
    assemblyConstituencies: ["Avinashi", "Dharapuram", "Kangeyam", "Madathukulam", "Palladam", "Tiruppur North", "Tiruppur South", "Udumalaipettai"],
    lokSabhaConstituencies: ["Coimbatore", "Erode", "Nilgiris", "Pollachi", "Tiruppur"],
  },
  tiruvallur: {
    code: "TAL",
    headquarters: "Tiruvallur",
    established: "1 July 1997",
    predecessor: "Chingleput",
    areaKm2: 3444.2,
    population: 3728104,
    popDensityPerKm2: 1082,
    revenueDivisions: ["Ponneri", "Tiruttani", "Tiruvallur"],
    taluks: ["Avadi", "Gummidipoondi", "Pallipattu", "Ponneri", "Poonamallee", "R. K. Pettai", "Tiruttani", "Tiruvallur", "Uthukkottai"],
    assemblyConstituencies: ["Avadi", "Gummidipoondi", "Ponneri", "Poonamallee", "Tiruttani", "Tiruvallur"],
    lokSabhaConstituencies: ["Arakkonam", "Tiruvallur"],
  },
  tiruvannamalai: {
    code: "TAN",
    headquarters: "Tiruvannamalai",
    established: "30 September 1989",
    predecessor: "North Arcot",
    areaKm2: 6191,
    population: 2464875,
    popDensityPerKm2: 398,
    revenueDivisions: ["Aarani", "Cheyyar", "Tiruvannamalai"],
    taluks: ["Aarani", "Chengam", "Chetpet", "Cheyyar", "Jamunamarathur", "Kalasapakkam", "Kilpennathur", "Polur", "Thandarampattu", "Tiruvannamalai", "Vandavasi", "Vembakkam"],
    assemblyConstituencies: ["Arani", "Chengam", "Cheyyar", "Kalasapakkam", "Kilpennathur", "Polur", "Tiruvannamalai", "Vandavasi"],
    lokSabhaConstituencies: ["Arani", "Tiruvannamalai"],
  },
  tiruvarur: {
    code: "TAR",
    headquarters: "Thiruvarur",
    established: "1 January 1997",
    predecessor: "Nagapattinam and Thanjavur",
    areaKm2: 2161,
    population: 1264277,
    popDensityPerKm2: 585,
    revenueDivisions: ["Mannargudi", "Tiruvarur"],
    taluks: ["Koothanallur", "Kudavasal", "Mannargudi", "Nannilam", "Needamangalam", "Thiruthuraipoondi", "Tiruvarur", "Valangaiman", "Muthupet"],
    assemblyConstituencies: ["Mannargudi", "Nannilam", "Thiruthuraipoondi", "Tiruvarur"],
    lokSabhaConstituencies: ["Nagapattinam", "Thanjavur"],
  },
  vellore: {
    code: "VEL",
    headquarters: "Vellore",
    established: "30 September 1989",
    predecessor: "North Arcot",
    areaKm2: 2222.1,
    population: 1614242,
    popDensityPerKm2: 726,
    revenueDivisions: ["Gudiyatham", "Vellore"],
    taluks: ["Anaicut", "Gudiyatham", "Pernampattu", "Katpadi", "Kilvaithinankuppam", "Vellore"],
    assemblyConstituencies: ["Anaikattu", "Gudiyatham", "Katpadi", "Kilvaithinankuppam", "Vellore"],
    lokSabhaConstituencies: ["Arakkonam", "Vellore"],
  },
  viluppuram: {
    code: "VIL",
    headquarters: "Viluppuram",
    established: "30 September 1993",
    predecessor: "South Arcot",
    areaKm2: 3725.5,
    population: 2093003,
    popDensityPerKm2: 562,
    revenueDivisions: ["Tindivanam", "Villupuram"],
    taluks: ["Gingee", "Kandachipuram", "Marakkanam", "Melmalayanur", "Tindivanam", "Vanur", "Vikravandi", "Villupuram", "Thiruvennainallur"],
    assemblyConstituencies: ["Gingee", "Mailam", "Tindivanam", "Vanur", "Villupuram", "Vikravandi"],
    lokSabhaConstituencies: ["Arani", "Villupuram"],
  },
  virudhunagar: {
    code: "VIR",
    headquarters: "Virudhunagar",
    established: "15 March 1985",
    predecessor: "Ramanathapuram",
    areaKm2: 4288,
    population: 1942288,
    popDensityPerKm2: 453,
    revenueDivisions: ["Aruppukkottai", "Sattur", "Sivakasi"],
    taluks: ["Aruppukkottai", "Kariapatti", "Rajapalayam", "Sattur", "Sivakasi", "Srivilliputhur", "Tiruchuli", "Virudhunagar", "Watrap", "Vembakottai"],
    assemblyConstituencies: ["Aruppukkottai", "Rajapalayam", "Sattur", "Sivakasi", "Srivilliputhur", "Tiruchuli", "Virudhunagar"],
    lokSabhaConstituencies: ["Ramanathapuram", "Tenkasi", "Virudhunagar"],
  },
};

export function getDistrictAdminDetails(slug: string): DistrictAdminDetails | undefined {
  const key = slug.toLowerCase().replace(/^the-/, "");
  return TAMIL_NADU_DISTRICT_ADMIN_DATA[slug.toLowerCase()] || TAMIL_NADU_DISTRICT_ADMIN_DATA[key];
}
