import { ExplorerPlace } from "./canonical-places";

export const VERIFIED_TN_HILL_PLACES: Record<string, ExplorerPlace> = {
  "manjolai": {
    id: "p-manjolai-hills",
    canonicalName: "Manjolai Tea Estates & KMTR",
    name: "Manjolai",
    slug: "manjolai",
    entityType: "HILL",
    district: "Tirunelveli",
    state: "Tamil Nadu",
    country: "India",
    latitude: 8.6254,
    longitude: 77.3872,
    categories: ["hills", "nature", "wildlife", "tourist-places"],
    primaryCategory: "hills",
    tagline: "High-altitude tea estates & mist-shrouded sanctuary inside Kalakkad Mundanthurai Tiger Reserve",
    description: "Nestled at 1,162m elevation in the Kalakkad Mundanthurai Tiger Reserve (KMTR) in Ambasamudram taluk, Manjolai is a serene tea plantation hill haven surrounded by dense evergreen rainforests, Kodayar Dam reservoirs, and rich wildlife habitats.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Tirunelveli District Administration & TN Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["manjolai", "tirunelveli", "ambasamudram", "kmtr", "tea_estates", "hills", "wildlife"],
    highlights: [
      "Manjolai Organic Tea Plantations",
      "Upper Kodayar Dam Viewpoint",
      "Oothu & Kakkachi Scenic Tea Slopes",
      "Manimuthar Waterfalls Gate Checkpoint"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to March",
      duration: "Full day",
      accessPermissions: "⚠️ Regulated entry by TN Forest Dept at Manimuthar Gate. Prior pass mandatory. Single-use plastic strictly prohibited.",
      forestPermitRequired: true,
      roadCondition: "Winding forest mountain road; drive cautiously."
    },
    travelOrigins: ["madurai", "coimbatore"],
    geographicRegion: "Southern Western Ghats",
    taluk: "Ambasamudram",
    nearbyTown: "Ambasamudram (28 km)"
  },
  "pachamalai-hills": {
    id: "p-pachamalai-hills",
    canonicalName: "Pachamalai Hills & Top Sengattupatti",
    name: "Pachamalai Hills",
    slug: "pachamalai-hills",
    entityType: "HILL",
    district: "Tiruchirappalli",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.3050,
    longitude: 78.6320,
    categories: ["hills", "nature", "trekking", "tourist-places"],
    primaryCategory: "hills",
    tagline: "Verdant Eastern Ghats mountain range & Malayali tribal eco-tourism hub",
    description: "Pachamalai (Green Hills) is a scenic Eastern Ghats hill range spanning Tiruchirappalli, Perambalur, and Salem districts. Top Sengattupatti in Thuraiyur taluk serves as the eco-tourism headquarters, featuring forest treehouses, herbal trails, and traditional tribal villages.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Tiruchirappalli District Administration & Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["pachamalai", "trichy", "thuraiyur", "eastern_ghats", "hills", "eco_tourism", "treehouses"],
    highlights: [
      "Top Sengattupatti Eco-Tourism Hub",
      "Koraiyar & Mangalam Waterfalls Trails",
      "Malayali Tribal Heritage Villages",
      "Eastern Ghats Ridge Panoramas"
    ],
    placeType: "region",
    metadata: {
      bestTime: "September to February",
      duration: "1-2 days",
      accessPermissions: "Open public ghat road from Thuraiyur. Forest Dept treehouse booking available at Top Sengattupatti.",
      roadCondition: "Good asphalt ghat road via Thuraiyur."
    },
    travelOrigins: ["trichy", "salem"],
    geographicRegion: "Eastern Ghats Cauvery Belt",
    taluk: "Thuraiyur",
    nearbyTown: "Thuraiyur (30 km)"
  },
  "bargur-hills": {
    id: "p-bargur-hills",
    canonicalName: "Bargur Hills (Anthiyur Range)",
    name: "Bargur Hills",
    slug: "bargur-hills",
    entityType: "HILL",
    district: "Erode",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.8250,
    longitude: 77.5350,
    categories: ["hills", "wildlife", "nature", "trekking"],
    primaryCategory: "hills",
    tagline: "Dense sandal forest ghat range & Thamaraikarai plateau in Anthiyur, Erode",
    description: "Located in Anthiyur taluk of Erode District (bordering Karnataka and Salem), Bargur Hills is a rugged Eastern-Western Ghats transition range. Famous for Thamaraikarai plateau, indigenous Bargur cattle, sandalwood forests, and 22 winding hairpin bends.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Erode District Administration & Forest Dept (District corrected from Salem lead)",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["bargur", "erode", "anthiyur", "thamaraikarai", "hills", "sandalwood", "wildlife"],
    highlights: [
      "Thamaraikarai Plateau Viewpoint",
      "Anthiyur Ghat Road 22 Hairpin Bends",
      "Indigenous Bargur Cattle Breeding Tract",
      "Palar River Basin Reserve Forest"
    ],
    placeType: "region",
    metadata: {
      bestTime: "October to March",
      duration: "Day trip",
      accessPermissions: "⚠️ Active forest checkpoint at Anthiyur base. Night vehicle driving restricted (6 PM to 6 AM).",
      forestPermitRequired: true,
      roadCondition: "Winding 22 hairpin bend state highway ghat road."
    },
    travelOrigins: ["salem", "coimbatore", "trichy"],
    geographicRegion: "Erode & Sathyamangalam Region",
    taluk: "Anthiyur",
    nearbyTown: "Anthiyur (32 km)"
  },
  "meghamalai": {
    id: "p-meghamalai-hills",
    canonicalName: "Megamalai (High Wavy Mountains)",
    name: "Meghamalai",
    slug: "meghamalai",
    entityType: "HILL",
    district: "Theni",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.6845,
    longitude: 77.4080,
    categories: ["hills", "nature", "wildlife", "tourist-places"],
    primaryCategory: "hills",
    tagline: "Cloud-capped mountain range & tea estate wilderness in Megamalai Tiger Reserve",
    description: "Rising to 1,500m elevation in the Western Ghats of Theni District, Megamalai (High Wavy Mountains) is an eco-sensitive hill sanctuary featuring tea gardens, Manalar & Venniyar dams, cardamon estates, and wildlife in Megamalai Tiger Reserve.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Theni District Administration & TN Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["meghamalai", "megamalai", "theni", "highwavys", "tea_estates", "hills", "tiger_reserve"],
    highlights: [
      "Highwavys Estate Lake & Tea Slopes",
      "Manalar Dam & Waterfall Viewpoint",
      "Megamalai Cloud Peak Mountain Ridge",
      "Srivilliputhur-Megamalai Tiger Reserve"
    ],
    placeType: "town",
    metadata: {
      bestTime: "September to May",
      duration: "1-2 days",
      accessPermissions: "⚠️ Regulated entry pass at Chinnamanur check post. Plastic ban strictly enforced.",
      forestPermitRequired: true,
      roadCondition: "Scenic 18 hairpin bend mountain road from Chinnamanur."
    },
    travelOrigins: ["madurai", "coimbatore"],
    geographicRegion: "Theni & Western Ghats",
    taluk: "Andipatti",
    nearbyTown: "Chinnamanur (28 km)"
  },
  "pandrimalai": {
    id: "p-pandrimalai-hills",
    canonicalName: "Pandrimalai Hills",
    name: "Pandrimalai",
    slug: "pandrimalai",
    entityType: "HILL",
    district: "Dindigul",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.2350,
    longitude: 77.7120,
    categories: ["hills", "nature", "temples", "trekking"],
    primaryCategory: "hills",
    tagline: "Peaceful coffee & pepper hill village in the lower Palani Hills range near Bathalagundu",
    description: "Perched at 1,300m in the lower Palani Hills of Dindigul District, Pandrimalai is an unspoiled mountain village surrounded by coffee estates, black pepper plantations, and ancient Murugan temple peaks.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Dindigul District Administration",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 97,
    lastVerifiedAt: "2026-10-01T18:40:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["pandrimalai", "dindigul", "palani_hills", "bathalagundu", "coffee_estates", "hills", "trekking"],
    highlights: [
      "Panrimalai Balamurugan Temple Peak",
      "Aromatic Coffee & Pepper Estate Walk",
      "Low Palani Hills Ravine Panoramas",
      "Offbeat Mountain Trekking Trails"
    ],
    placeType: "village",
    metadata: {
      bestTime: "October to March",
      duration: "Day trip",
      accessPermissions: "Open public access via Bathalagundu-Pandrimalai ghat road.",
      roadCondition: "Paved mountain road from Bathalagundu."
    },
    travelOrigins: ["madurai", "coimbatore", "trichy"],
    geographicRegion: "Palani Hills & Dindigul",
    taluk: "Kodaikanal / Dindigul West",
    nearbyTown: "Bathalagundu (22 km)"
  },
  "agastheyarkoodam": {
    id: "p-agastheyarkoodam-peak",
    canonicalName: "Agastheyarkoodam Peak & Pothigai Malai",
    name: "Agastheyarkoodam",
    slug: "agastheyarkoodam",
    entityType: "HILL",
    district: "Tirunelveli",
    state: "Tamil Nadu",
    country: "India",
    latitude: 8.6145,
    longitude: 77.2485,
    categories: ["mountains", "trekking", "wildlife", "nature"],
    primaryCategory: "mountains",
    tagline: "Sacred 1,868m Western Ghats peak, birthplace of Tamil language & UNESCO Biosphere Reserve",
    description: "Standing at 1,868m MSL in the Agasthyamalai Biosphere Reserve, Agastheyarkoodam (Pothigai Malai) is revered as the spiritual abode of Sage Agastya and cradle of the Tamil language. Famed for rare medicinal herbs, Neelakurinji blooms, and cloud forest trekking.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "UNESCO Biosphere Reserve & Kerala/TN Forest Depts",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:50:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["agastheyarkoodam", "pothigai_malai", "agasthyamalai", "tirunelveli", "trekking", "mountains", "unesco_reserve"],
    highlights: [
      "1,868m Majestic Agasthyamalai Peak",
      "Sacred Sage Agastya Shrine",
      "UNESCO Agasthyamalai Biosphere Reserve",
      "Rare Medicinal Flora & Cloud Forests"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "January to February (Permitted Season)",
      duration: "2 days trek",
      accessPermissions: "⚠️ Strictly regulated eco-trekking pass issued during Jan-Feb season by Forest Dept. Authorized guide mandatory.",
      forestPermitRequired: true,
      roadCondition: "High altitude wilderness trek."
    },
    travelOrigins: ["madurai", "coimbatore"],
    geographicRegion: "Southern Western Ghats",
    taluk: "Ambasamudram",
    nearbyTown: "Ambasamudram (45 km)"
  }
};
