import { ExplorerPlace } from "./canonical-places";

export const TREKKING_NATURE_PLACES: Record<string, ExplorerPlace> = {
  "nagalapuram-hills": {
    id: "p-nagalapuram-hills",
    canonicalName: "Nagalapuram Hills & Waterfalls",
    name: "Nagalapuram Hills",
    slug: "nagalapuram-hills",
    entityType: "POI",
    district: "Tirupati (Chittoor)",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.3980,
    longitude: 79.7890,
    categories: ["trekking", "waterfalls", "wildlife", "nature"],
    primaryCategory: "trekking",
    tagline: "Eastern Ghats stream trek with crystal-clear canyon pools & natural rock slides",
    description: "Nagalapuram is a renowned wilderness stream trek located in the Eastern Ghats of Tirupati/Chittoor district, Andhra Pradesh (~75 km from Chennai). The trail follows a mountain stream through dense forest, leading to three deep natural rock pools fed by cascading waterfalls.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Andhra Pradesh Forest Department",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["nagalapuram", "trekking", "waterfall_trekking", "mountain_trekking", "canyon_pools", "andhra_pradesh", "forest_trails"],
    highlights: [
      "Three Deep Natural Canyon Pools",
      "Eastern Ghats Stream Bed Trek",
      "Natural Water Rock Slides",
      "Sadasiva Kona Wilderness Surroundings"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "August to January (Post-Monsoon)",
      duration: "Full day (6-7 hrs trek)",
      accessPermissions: "⚠️ AP Forest Dept entry check post at Nagalapuram Dam. Life jackets advised for deep pools. Plastic strictly banned.",
      forestPermitRequired: true,
      roadCondition: "Paved road to Nagalapuram Dam trailhead."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Eastern Ghats Border Range",
    taluk: "Nagalapuram",
    nearbyTown: "Nagalapuram (8 km) / Utthukottai (20 km)",
    distanceFromChennaiKm: 75,
    durationFromChennaiHours: 2.0
  },

  "tada-falls": {
    id: "p-tada-falls",
    canonicalName: "Tada Falls (Ubbalamadugu Falls)",
    name: "Tada Falls",
    slug: "tada-falls",
    entityType: "POI",
    district: "Tirupati (Chittoor)",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.6025,
    longitude: 79.8450,
    categories: ["waterfalls", "trekking", "nature"],
    primaryCategory: "waterfalls",
    tagline: "Rocky ravine trail leading to a hidden forest waterfall in the Kambakam hills",
    description: "Located in the Kambakam forest near Varadaiahpalem in Tirupati district, Andhra Pradesh (~85 km from Chennai), Tada Falls (Ubbalamadugu) is a favorite adventure hike featuring boulder hopping along a forest riverbed to a secluded waterfall basin.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "AP Eco-Tourism & Forest Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["tada_falls", "ubbalamadugu", "waterfalls", "waterfall_trekking", "boulder_climbing", "andhra_pradesh", "kambakam"],
    highlights: [
      "10 km Round-Trip Forest & Riverbed Hike",
      "Challenging Boulder Hopping Sections",
      "Hidden Waterfall Ravine Basin",
      "Kambakam Reserve Forest Canopy"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "September to February",
      duration: "5-6 hours hike",
      accessPermissions: "Ticketed entry at Varadaiahpalem AP Forest Dept gate. Sturdy footwear recommended for slippery rocks.",
      forestPermitRequired: true,
      roadCondition: "Asphalt road to forest check post parking."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Eastern Ghats Border Range",
    taluk: "Varadaiahpalem",
    nearbyTown: "Varadaiahpalem (10 km) / Tada (25 km)",
    distanceFromChennaiKm: 85,
    durationFromChennaiHours: 2.2
  },

  "swamimalai-yelagiri": {
    id: "p-swamimalai-yelagiri",
    canonicalName: "Swamimalai Hills (Yelagiri)",
    name: "Swamimalai Hills",
    slug: "swamimalai-hills",
    entityType: "HILL",
    district: "Tirupattur",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.5780,
    longitude: 78.6410,
    categories: ["hills", "trekking", "nature"],
    primaryCategory: "hills",
    tagline: "Highest peak in Yelagiri Hills at 1,438m MSL offering panoramic valley vistas",
    description: "Swamimalai is the highest peak in the Yelagiri hill range (1,438m MSL) in Tirupattur District, Tamil Nadu (~230 km from Chennai). A popular 3 km step-and-dirt trail ascends from Mangalam village through green hamlets to a hilltop Shiva shrine.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Tamil Nadu Tourism & Tirupattur District Admin",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["swamimalai", "yelagiri", "tirupattur", "hills", "hill_hiking", "mountain_trekking", "highest_peak"],
    highlights: [
      "1,438m Highest Yelagiri Mountain Peak",
      "3 km Scenic Step & Forest Hike",
      "Hilltop Trident Shiva Temple Rock",
      "Panoramic Views over Javadhu Hills Valley"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "September to March",
      duration: "3-4 hours round trip",
      accessPermissions: "Open public trail starting from Mangalam village base."
    },
    travelOrigins: ["chennai", "salem"],
    geographicRegion: "Yelagiri & Javadhu Hills",
    taluk: "Tirupattur",
    nearbyTown: "Yelagiri Town (4 km) / Jolarpet (21 km)",
    distanceFromChennaiKm: 230,
    durationFromChennaiHours: 4.5
  },

  "vedanthangal-bird-sanctuary": {
    id: "p-vedanthangal-sanctuary",
    canonicalName: "Vedanthangal Bird Sanctuary",
    name: "Vedanthangal Bird Sanctuary",
    slug: "vedanthangal-bird-sanctuary",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.5450,
    longitude: 79.8550,
    categories: ["wildlife", "nature", "tourist-places"],
    primaryCategory: "wildlife",
    tagline: "India's oldest waterbird sanctuary home to 40,000 migratory birds during winter",
    description: "Established in 1798 in Maduranthakam taluk, Chengalpattu district (~75 km from Chennai), Vedanthangal is India's oldest protected bird sanctuary. Over 40,000 migratory waterbirds including painted storks, pelicans, herons, and ibises nest in Barringtonia trees.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "TN Forest Department (Wildlife Wing)",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["vedanthangal", "birdwatching", "bird_sanctuary", "chengalpattu", "wildlife", "migratory_birds", "nature_walks"],
    highlights: [
      "40,000+ Migratory Nesting Waterbirds",
      "Barringtonia Tree Wetland Ecosystem",
      "Watchtowers with Telescope Views",
      "Paved Lake Bund Nature Walkway"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "November to March (Peak Nesting Season)",
      duration: "2-3 hours",
      accessPermissions: "Ticketed entry pass by TN Wildlife Dept. Open 6:00 AM - 6:00 PM."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "South Chennai Coastal",
    taluk: "Maduranthakam",
    nearbyTown: "Maduranthakam (12 km) / Chengalpattu (30 km)",
    distanceFromChennaiKm: 75,
    durationFromChennaiHours: 1.8
  },

  "kailasakona-waterfall": {
    id: "p-kailasakona-waterfall",
    canonicalName: "Kailasakona Waterfall & Temple",
    name: "Kailasakona Waterfall",
    slug: "kailasakona-waterfall",
    entityType: "POI",
    district: "Tirupati (Chittoor)",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.3440,
    longitude: 79.6450,
    categories: ["waterfalls", "temples", "nature"],
    primaryCategory: "waterfalls",
    tagline: "Perennial sacred forest waterfall flowing from Nagari Hills near Puttur",
    description: "Located near Puttur in Tirupati district, Andhra Pradesh (~92 km from Chennai), Kailasakona is a sacred perennial waterfall dropping 40 feet into a clear pool. Known for mineral-rich waters and a small cave shrine dedicated to Lord Shiva and Parvati.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "AP Tourism Development Corporation",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["kailasakona", "waterfalls", "puttur", "andhra_pradesh", "nagari_hills", "shiva_temple", "nature_walks"],
    highlights: [
      "40-foot Perennial Mineral Waterfall",
      "Ancient Lord Kailasanatheswara Cave Shrine",
      "Nagari Hills Green Forest Setting",
      "Easy Family Walkway Access"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "September to February",
      duration: "2 hours",
      accessPermissions: "Open public access. Nominal APTDC parking fee."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Eastern Ghats Border Range",
    taluk: "Narayanavanam",
    nearbyTown: "Puttur (10 km) / Nagari (12 km)",
    distanceFromChennaiKm: 92,
    durationFromChennaiHours: 2.2
  },

  "vallimalai-hills": {
    id: "p-vallimalai-hills",
    canonicalName: "Vallimalai Hills & Subramanya Temple",
    name: "Vallimalai Hills",
    slug: "vallimalai-hills",
    entityType: "HILL",
    district: "Vellore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9980,
    longitude: 79.2450,
    categories: ["temples", "hills", "heritage", "trekking"],
    primaryCategory: "temples",
    tagline: "Sacred Murugan cave hill, Jain rock reliefs & birthplace of Goddess Valli near Katpadi",
    description: "Perched atop a granite hill near Katpadi in Vellore District (~120 km from Chennai), Vallimalai is legendary as the birthplace of Goddess Valli. Features an ancient rock-cut Murugan cave temple, sacred natural pools (Valli Sunai), and 9th-century Jain rock sculptures.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "HR&CE Dept & ASI Chennai Circle",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["vallimalai", "vellore", "katpadi", "murugan_temple", "jain_caves", "hill_hiking", "pilgrimage_routes"],
    highlights: [
      "Rock-Cut Rock Sanctuary of Lord Murugan",
      "Valli Sunai Sacred Mountain Spring Pool",
      "9th-Century Western Ganga Jain Tirthankara Reliefs",
      "300-Step Scenic Hill Climb"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to March",
      duration: "3 hours",
      accessPermissions: "Open public access. Steps leading to hilltop temple."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Vellore & Palar Valley",
    taluk: "Katpadi",
    nearbyTown: "Katpadi (18 km) / Vellore (25 km)",
    distanceFromChennaiKm: 120,
    durationFromChennaiHours: 2.8
  },

  "tirumala-alipiri-footpath": {
    id: "p-tirumala-alipiri-footpath",
    canonicalName: "Tirumala Alipiri Footpath Trek",
    name: "Tirumala Alipiri Footpath",
    slug: "tirumala-alipiri-footpath",
    entityType: "POI",
    district: "Tirupati",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.6520,
    longitude: 79.3990,
    categories: ["trekking", "temples", "heritage"],
    primaryCategory: "trekking",
    tagline: "Sacred 3,550-step pilgrim mountain trek through Seshachalam hills to Tirumala",
    description: "Starting from Alipiri Mettu in Tirupati (~150 km from Chennai), the Alipiri Footpath is the historic 9 km pilgrim trekking trail ascending 3,550 stone steps through the Seshachalam Seven Hills to the sacred Sri Venkateswara Temple in Tirumala.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "Tirumala Tirupati Devasthanams (TTD)",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["alipiri", "tirumala", "tirupati", "pilgrimage_routes", "mountain_trekking", "andhra_pradesh", "seshachalam"],
    highlights: [
      "3,550 Sacred Stone Steps Ascent",
      "Galigopuram High Point View (Step 2,000)",
      "Covered Pedestrian Way with Solar Lighting",
      "Seshachalam Biosphere Forest Scenery"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "Throughout the year (Early Morning or Night)",
      duration: "4-5 hours climb",
      accessPermissions: "TTD security check & luggage scanning at Alipiri base. Free Divya Darshan tokens issued at Galigopuram."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Seshachalam Hills",
    taluk: "Tirupati Urban",
    nearbyTown: "Tirupati City (4 km)",
    distanceFromChennaiKm: 150,
    durationFromChennaiHours: 3.5
  },

  "gudiyam-caves": {
    id: "p-gudiyam-caves",
    canonicalName: "Gudiyam Caves (Prehistoric Rock Shelters)",
    name: "Gudiyam Caves",
    slug: "gudiyam-caves",
    entityType: "POI",
    district: "Tiruvallur",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.2250,
    longitude: 79.8780,
    categories: ["museums", "trekking", "nature", "heritage"],
    primaryCategory: "museums",
    tagline: "Paleolithic Stone Age cave shelters in reserve forest near Poondi Reservoir",
    description: "Located 10 km from Poondi in Tiruvallur District (~60 km from Chennai), Gudiyam Caves are 16 prehistoric natural rock shelters discovered by Robert Bruce Foote in 1863. Human occupation dates back 100,000+ years to the Lower Paleolithic Stone Age.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Archaeological Survey of India & TN Archaeology Dept",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["gudiyam", "caves", "tiruvallur", "poondi", "paleolithic", "archaeological_sites", "forest_trails"],
    highlights: [
      "100,000-Year-Old Paleolithic Cave Shelters",
      "Natural Conglomerate Rock Formations",
      "5 km Forest Trail Walk from Gudiyam Village",
      "Proximity to Poondi Archaeological Museum"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to February",
      duration: "4 hours trail walk",
      accessPermissions: "Inside reserve forest. Local guide recommended from Gudiyam village.",
      forestPermitRequired: true,
      roadCondition: "Dirt track from Poondi-Gudiyam road."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Tiruvallur",
    nearbyTown: "Poondi (10 km) / Tiruvallur (25 km)",
    distanceFromChennaiKm: 60,
    durationFromChennaiHours: 1.5
  },

  "mamandur-forest": {
    id: "p-mamandur-forest",
    canonicalName: "Mamandur Forest & Seshachalam Eco-Tourism",
    name: "Mamandur Forest",
    slug: "mamandur-forest",
    entityType: "POI",
    district: "Tirupati (Kadapa)",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.7250,
    longitude: 79.4850,
    categories: ["wildlife", "nature", "trekking"],
    primaryCategory: "wildlife",
    tagline: "Red sanders reserve forest & eco-tourism center in Seshachalam Biosphere Reserve",
    description: "Situated on the Chennai-Kadapa highway (~110 km from Chennai), Mamandur is a historic forest eco-tourism station inside the UNESCO Seshachalam Biosphere Reserve. Known for rare Red Sanders trees, birdwatching trails, and colonial forest bungalows.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "AP Forest Department (Eco-Tourism)",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 98,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["mamandur", "seshachalam", "red_sanders", "forest_trails", "birdwatching", "andhra_pradesh", "eco_tourism"],
    highlights: [
      "Protected Red Sanders Forest Canopy",
      "Seshachalam Biosphere Jungle Trails",
      "Birdwatching along Water Streams",
      "British-Era Heritage Forest Rest House"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to March",
      duration: "Half day",
      accessPermissions: "AP Forest Dept eco-tourism ticket at Mamandur forest center."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Seshachalam Hills",
    taluk: "Renigunta",
    nearbyTown: "Renigunta (15 km) / Tirupati (25 km)",
    distanceFromChennaiKm: 110,
    durationFromChennaiHours: 2.5
  },

  "kanchipuram-rural-trails": {
    id: "p-kanchipuram-rural-trails",
    canonicalName: "Tenneri & Kanchipuram Rural Hill Trails",
    name: "Kanchipuram Rural Hill Trails",
    slug: "kanchipuram-rural-trails",
    entityType: "POI",
    district: "Kanchipuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.8900,
    longitude: 79.8200,
    categories: ["nature", "trekking", "heritage"],
    primaryCategory: "nature",
    tagline: "Offbeat granite hillock trails, ancient lake bunds & countryside walks around Tenneri",
    description: "Located near Wallajahbad in Kanchipuram District (~70 km from Chennai), Tenneri and surrounding rural hillocks offer peaceful countryside trekking. Features granite boulder slopes, 1,000-year-old Chola irrigation lake bunds, and rustic village vistas.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    source: "Kanchipuram District Administration",
    sourceType: "COMMUNITY_VERIFIED",
    confidenceScore: 96,
    lastVerifiedAt: "2026-10-01T18:55:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["kanchipuram", "tenneri", "rural_trails", "hill_hiking", "heritage_trails", "nature_walks", "chola_lake"],
    highlights: [
      "Tenneri Historic Chola Lake Bund Walk",
      "Granite Boulder Hillock Hikes",
      "Peaceful Countryside Sunset Views",
      "Rustic Agrarian Village Surroundings"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "October to February",
      duration: "3 hours",
      accessPermissions: "Open public countryside trails."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "Central Chennai Heritage",
    taluk: "Wallajahbad",
    nearbyTown: "Wallajahbad (12 km) / Kanchipuram (20 km)",
    distanceFromChennaiKm: 70,
    durationFromChennaiHours: 1.6
  },

  "chembarambakkam-lake": {
    id: "p-chembarambakkam-lake",
    canonicalName: "Chembarambakkam Lake Viewpoint Walkway & Erikarai Road",
    name: "Chembarambakkam Lake Walkway",
    slug: "chembarambakkam-lake",
    entityType: "POI",
    district: "Kanchipuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0115,
    longitude: 80.0550,
    categories: ["dams", "rivers", "nature", "tourist-places"],
    primaryCategory: "rivers",
    tagline: "Panoramic 15 sq km reservoir embankment walkway, sunset vistas & birdwatching spot on Erikarai Road",
    description: "Located along Erikarai Road in Chembarambakkam (~25 km west of Central Chennai), Chembarambakkam Lake Viewpoint Walkway offers a scenic 4 km paved lake bund walkway overlooking one of Chennai's primary freshwater drinking reservoirs. Popular for breezy sunset strolls, cycling, birdwatching, and views across the vast 15 sq km water body.",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    verified: true,
    source: "TN Public Works Dept & Kanchipuram District Admin",
    sourceType: "OFFICIAL_GOVERNMENT",
    confidenceScore: 99,
    lastVerifiedAt: "2026-10-01T18:57:00Z",
    verificationStatus: "VERIFIED",
    dataVersion: 1,
    tags: ["chembarambakkam", "chembarabakkam", "erikarai_road", "viewpoint_walkway", "lake", "reservoir", "chennai", "sunset"],
    highlights: [
      "4 km Paved Erikarai Lake Bund Walkway",
      "Panoramas across 15 sq km Water Reservoir",
      "Sunset & Sunrise Photography Spot",
      "Winter Migratory Birdwatching Spot"
    ],
    placeType: "attraction",
    metadata: {
      bestTime: "5:30 AM - 8:30 AM & 4:30 PM - 7:00 PM",
      duration: "2 hours",
      accessPermissions: "Open public walkway on Erikarai Road. Bund access restricted during heavy monsoon discharge gates opening."
    },
    travelOrigins: ["chennai"],
    geographicRegion: "North & West Chennai",
    taluk: "Kundrathur / Sriperumbudur",
    nearbyTown: "Punamallee (5 km) / Central Chennai (25 km)",
    distanceFromChennaiKm: 25,
    durationFromChennaiHours: 0.6
  },

  "scuba-diving-rameshwaram": {
    id: "p-scuba-diving-rameshwaram",
    canonicalName: "Scuba Diving in Rameswaram (Olaikuda)",
    name: "Scuba Diving in Rameswaram",
    slug: "scuba-diving-rameshwaram",
    entityType: "POI",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.2974,
    longitude: 79.3242,
    categories: ["adventure", "coastal", "beaches"],
    primaryCategory: "adventure",
    tagline: "PADI certified scuba diving & coral reef discovery in Gulf of Mannar marine biosphere",
    description: "Explore Gulf of Mannar marine national park fringing reefs, sea anemones, clownfish, and sea turtles with certified PADI dive masters at Holy Island Water Sports / Olaikuda Beach.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.9,
    reviewsCount: 4200,
    tags: ["scuba_diving", "rameswaram", "coral_reef", "gulf_of_mannar", "water_sports", "padi"],
    highlights: ["Gulf of Mannar Coral Reefs", "1-on-1 PADI Instructor Guidance", "4K Underwater GoPro Video", "Marine Biosphere Sanctuary"]
  },

  "paragliding-yelagiri": {
    id: "p-paragliding-yelagiri",
    canonicalName: "Paragliding in Yelagiri",
    name: "Paragliding in Yelagiri",
    slug: "paragliding-yelagiri",
    entityType: "POI",
    district: "Tirupathur",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.5833,
    longitude: 78.6333,
    categories: ["adventure", "hills"],
    primaryCategory: "adventure",
    tagline: "Tandem paragliding soaring over the Jawadhu hill ranges and orchards at 920m altitude",
    description: "Organized by Yelagiri Adventure Sports Association (YASA) at Kottur/Raneri launching points. Experience smooth thermal flight with certified pilots overlooking verdant valleys.",
    image: "https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.8,
    reviewsCount: 3800,
    tags: ["paragliding", "yelagiri", "aero_sports", "yasa", "tandem_flight", "hills"],
    highlights: ["920m Mountain Takeoff", "YASA Certified Pilots", "Tandem Flight", "GoPro Video Packages"]
  },

  "off-roading-kolli-hills": {
    id: "p-off-roading-kolli-hills",
    canonicalName: "Off Roading in Kolli Hills",
    name: "Off Roading in Kolli Hills",
    slug: "off-roading-kolli-hills",
    entityType: "POI",
    district: "Namakkal",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.2485,
    longitude: 78.3387,
    categories: ["adventure", "offroad", "hills"],
    primaryCategory: "offroad",
    tagline: "70 continuous hairpin bends ascending 1,300m MSL through rugged Eastern Ghats terrain",
    description: "India's premier winding mountain ghat road with 70 consecutive numbered hairpin curves and rugged estate tracks connecting Solakkadu and Semmedu across pepper and coffee estates.",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.9,
    reviewsCount: 15400,
    tags: ["offroad", "kolli_hills", "70_hairpin_bends", "namakkal", "4x4", "ghat_road"],
    highlights: ["70 Numbered Hairpin Bends", "Seekuparai Viewpoint", "Agaya Gangai Trailhead", "Pepper & Coffee Estates"]
  },

  "trek-agasthiyar-falls": {
    id: "p-trek-agasthiyar-falls",
    canonicalName: "Trek to Agasthiyar Falls",
    name: "Trek to Agasthiyar Falls",
    slug: "trek-agasthiyar-falls",
    entityType: "POI",
    district: "Tirunelveli",
    state: "Tamil Nadu",
    country: "India",
    latitude: 8.7042,
    longitude: 77.3683,
    categories: ["trekking", "waterfalls", "wildlife"],
    primaryCategory: "trekking",
    tagline: "Perennial 25m herbal waterfall inside Kalakkad Mundanthurai Tiger Reserve",
    description: "Originating high in the bio-rich Podhigai Hills along the Thamirabarani River, Agasthiyar Falls is revered for medicinal forest waters. A short scenic trek through KMTR leads up to Kalyanatheertham.",
    image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.8,
    reviewsCount: 18200,
    tags: ["agasthiyar_falls", "papanasam", "kmtr", "trekking", "waterfalls", "tirunelveli"],
    highlights: ["KMTR Tiger Reserve Buffer", "Thamirabarani River Trek", "Herbal Mineral Waters", "Kalyanatheertham Pool"]
  },

  "rock-climbing-gingee-fort": {
    id: "p-rock-climbing-gingee-fort",
    canonicalName: "Rock Climbing at Gingee Fort",
    name: "Rock Climbing at Gingee Fort",
    slug: "rock-climbing-gingee-fort",
    entityType: "POI",
    district: "Viluppuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.2536,
    longitude: 79.4181,
    categories: ["adventure", "heritage", "hills"],
    primaryCategory: "adventure",
    tagline: "Natural granite boulder towers & 800ft vertical rock climbs on the Troy of the East peaks",
    description: "Scale giant granite boulder problems and stone-cut fortress ascents across Rajagiri, Krishnagiri, and Chandrayandurg peaks with panoramic views of the Viluppuram plains.",
    image: "https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.8,
    reviewsCount: 6400,
    tags: ["rock_climbing", "gingee_fort", "bouldering", "rajagiri", "viluppuram", "heritage"],
    highlights: ["800ft Monolithic Peak", "1,200 Rock-Cut Steps", "Bouldering & Scrambling", "Hanging Chasm Bridge"]
  },

  "camping-kolli-hills": {
    id: "p-camping-kolli-hills",
    canonicalName: "Camping at Kolli Hills",
    name: "Camping at Kolli Hills",
    slug: "camping-kolli-hills",
    entityType: "POI",
    district: "Namakkal",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.2333,
    longitude: 78.3417,
    categories: ["adventure", "hills"],
    primaryCategory: "adventure",
    tagline: "Overnight wilderness dome tent camping amidst organic coffee & pepper estates at 1,300m elevation",
    description: "Unwind under pollution-free night skies with bonfires, estate walks, and cool misty mountain mornings in Selur Nadu and Seekuparai plateau.",
    image: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.8,
    reviewsCount: 3200,
    tags: ["camping", "kolli_hills", "stargazing", "estate_camping", "namakkal"],
    highlights: ["Campfire & Barbecue", "Coffee Estate Walks", "Stargazing Viewpoints", "Misty Cloud Line"]
  },

  "surfing-kovalam-chennai": {
    id: "p-surfing-kovalam-chennai",
    canonicalName: "Surfing at Kovalam Chennai",
    name: "Surfing at Kovalam Chennai",
    slug: "surfing-kovalam-chennai",
    entityType: "POI",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.7925,
    longitude: 80.2528,
    categories: ["adventure", "beaches", "coastal"],
    primaryCategory: "adventure",
    tagline: "India's surfing capital on scenic East Coast Road offering natural beach breaks & certified coaching",
    description: "Ride consistent coastal beach swells with ISA-certified instructors at Surf Turf and Bay of Life. Features world-class beginner foamie coaching, SUP paddleboarding, and ocean kayaking.",
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.9,
    reviewsCount: 11200,
    tags: ["surfing", "kovalam", "covelong", "chennai", "ecr", "water_sports"],
    highlights: ["Covelong Point Surf Break", "ISA Certified Surf Schools", "Surf Turf Beachfront Cafe", "Stand-Up Paddleboarding & Kayaks"]
  },

  "wildlife-safari-mudumalai": {
    id: "p-wildlife-safari-mudumalai",
    canonicalName: "Wildlife Safari in Mudumalai",
    name: "Wildlife Safari in Mudumalai",
    slug: "wildlife-safari-mudumalai",
    entityType: "POI",
    district: "The Nilgiris",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.5833,
    longitude: 76.5833,
    categories: ["adventure", "wildlife", "hills"],
    primaryCategory: "wildlife",
    tagline: "Forest department jeep & van safaris tracking Royal Bengal tigers, wild elephants, and Indian gaur",
    description: "Operating from the Theppakadu reception center in the foothills of Nilgiris. Experience wildlife tracking across Moyar river valleys with Asian elephants, spotted deer, wild dogs, and leopards.",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.8,
    reviewsCount: 38900,
    tags: ["mudumalai", "wildlife_safari", "nilgiris", "tiger_reserve", "elephants"],
    highlights: ["Bengal Tigers & Asian Elephants", "Theppakadu Elephant Camp", "Forest Van & 4x4 Gypsy Safari", "Moyar River Valley"]
  },

  "cave-exploring-sittanavasal": {
    id: "p-cave-exploring-sittanavasal",
    canonicalName: "Cave Exploring at Sittanavasal",
    name: "Cave Exploring at Sittanavasal",
    slug: "cave-exploring-sittanavasal",
    entityType: "POI",
    district: "Pudukkottai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.4578,
    longitude: 78.7495,
    categories: ["adventure", "heritage", "tourist-places"],
    primaryCategory: "heritage",
    tagline: "Explore 2nd-century BC Jain cavern beds and 7th-century fresco-secco lotus pond murals",
    description: "Scale granite rock steps up to Ezhadippattam natural cavern containing 17 ancient Jain ascetic stone beds with Tamil-Brahmi inscriptions, followed by the pillared Arivar Koil cave sanctum.",
    image: "https://images.unsplash.com/photo-1599831104328-b141d6a4571a?auto=format&fit=crop&w=1000&q=80",
    verified: true,
    rating: 4.8,
    reviewsCount: 7400,
    tags: ["sittanavasal", "cave_exploring", "jain_cave", "frescoes", "pudukkottai", "heritage"],
    highlights: ["7th-Century Fresco-Secco Murals", "Ezhadippattam 17 Stone Beds", "Tamil-Brahmi Script", "Granite Hill Trail"]
  }
};

